fedorov_kirill/Homework2
ArtemPrivet/FocusStartHomeworks pull request #20
Opened 2019-11-07 18:17 UTC by ikirillfedorov

2019-11-07 20:41 UTC, MisnikovRoman commented
Неверное название пула, должно быть 'fedorov_kirill/string_extension'

2019-11-07 20:45 UTC, MisnikovRoman commented
Минор: можно было разделить выполнение дз на 2 коммита, ну и конечно, развернутые названия коммитов (например, "Добавил метод разворачивающий слова в предложениях")

2019-11-07 20:57 UTC, MisnikovRoman requested changes
Оптимизировать первую функцию и изменить название пула

2019-11-07 20:57 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		var reversedWordsArray = [String]()
Тут лучше использовать метод `.map()`

2019-11-08 03:37 UTC, ikirillfedorov commented on Homework2/Homework2/String+Extensions.swift
> +		var reversedWordsArray = [String]()
Оптимизировал с помощью `.map()`

2019-11-08 16:12 UTC, MisnikovRoman approved these changes
Принято

2019-11-08 16:17 UTC, ArtemPrivet approved these changes

2019-11-08 16:23 UTC, MisnikovRoman commented
✅ Домашнее задание выполнено

2019-11-08 16:23 UTC, closed without merging