medvedev_mikhail/string_extension
ArtemPrivet/FocusStartHomeworks pull request #21
Opened 2019-11-07 20:17 UTC by c0dedbear

Создал новую ветку для второго задания, без коммитов с изменение файлов первого задания.

2019-11-07 21:07 UTC, MisnikovRoman requested changes
Убрать изменения из первого дз

2019-11-07 21:07 UTC, MisnikovRoman commented on Test/Test/AppDelegate.swift
> +		_ application: UIApplication, didFinishLaunchingWithOptions
Ветка изменилось, а изменения из первого дз так и остались 😢

2019-11-07 21:07 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +			reversedWords += (reversedString + separator)
Тут оптимально было бы использовать метод ‘.map()’

2019-11-07 21:07 UTC, MisnikovRoman commented on Test/Test.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = codedBear.Test;
Ну и изменений в настройках проекта тоже не должно быть

2019-11-08 09:22 UTC, c0dedbear commented on Test/Test/AppDelegate.swift
> +		_ application: UIApplication, didFinishLaunchingWithOptions
Сделал Revert коммита первого задания в этой ветке. Убрались ли изменения?

2019-11-08 09:22 UTC, c0dedbear commented on Homework2/Homework2/String+Extensions.swift
> +			reversedWords += (reversedString + separator)
Использовал. Изменения запушил.

2019-11-08 09:23 UTC, c0dedbear commented on Test/Test.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = codedBear.Test;
Это с первого задания подтянулось, вроде бы решил  revert'ом

2019-11-08 16:17 UTC, MisnikovRoman approved these changes

2019-11-08 16:24 UTC, ArtemPrivet approved these changes

2019-11-08 16:25 UTC, MisnikovRoman commented
✅ Домашнее задание 2 принято

2019-11-08 16:25 UTC, closed without merging