shelginskiy_igor/extension_string
ArtemPrivet/FocusStartHomeworks pull request #35
Opened 2019-11-09 08:59 UTC by Engwar

2019-11-09 14:04 UTC, MisnikovRoman requested changes

2019-11-09 14:04 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		let arrayOfwords = self.components(separatedBy: " ")
Переменные называются camelCase-ом (W)

2019-11-09 14:04 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		var string = ""
В названиях переменных следует избегать названий типов

2019-11-09 14:04 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		for char in 0..<arrayOfwords.count {
тут переменная явно не char

2019-11-09 14:04 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		for char in 0..<arrayOfwords.count {
и циклом лучше проходить не по индексам, а сразу по компонентам: `for word in words`

2019-11-09 14:04 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		for char in self {
Тут оптимально использовать метод filter

2019-11-10 13:20 UTC, Engwar commented on Homework2/Homework2/String+Extensions.swift
> +		for char in self {
filter может пропустить номер с буквой, или так же сделать switch $0 ?

2019-11-10 13:41 UTC, Engwar commented
<img width="864" alt="Screen Shot 2019-11-10 at 16 36 00" src="https://user-images.githubusercontent.com/31358134/68544912-d899d180-03d8-11ea-97b5-4fd945690d9f.png">
сделал filter но тест не работает если в номере есть буквы

2019-11-11 07:32 UTC, MisnikovRoman commented
> <img alt="Screen Shot 2019-11-10 at 16 36 00" width="864" src="https://user-images.githubusercontent.com/31358134/68544912-d899d180-03d8-11ea-97b5-4fd945690d9f.png">
> сделал filter но тест не работает если в номере есть буквы

скидывать код скриншотом - плохая затея ☹️

2019-11-11 08:02 UTC, MisnikovRoman commented
Но в целом у тебя метод фильтрации работает не так как в первой реализации. Плюс я не совсем понимаю идею разделения на `phoneNumber` и `digitNumber`

2019-11-11 11:15 UTC, Engwar commented
> Но в целом у тебя метод фильтрации работает не так как в первой реализации. Плюс я не совсем понимаю идею разделения на `phoneNumber` и `digitNumber`

Я просто подумал что так проще отслеживать например неверные номера которые начинаются с +9, +2 или +1. В тестах таких неверных номеров не было, но вдруг бы появились, поэтому я разделил проверку номеров на те что начинаются  с "+" и тех что начинаются с цифры. Про скрины учту...

2019-11-11 12:17 UTC, MisnikovRoman approved these changes

2019-11-11 12:18 UTC, ArtemPrivet approved these changes

2019-11-11 12:19 UTC, closed without merging