siniakov_eduard/String_extension
ArtemPrivet/FocusStartHomeworks pull request #37
Opened 2019-11-09 08:59 UTC by leningradspb

2019-11-09 14:11 UTC, MisnikovRoman requested changes

2019-11-09 14:11 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		let stringg = self
в названиях переменных не стоит использовать названия типов (даже с лишней буквой g)

2019-11-09 14:11 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +	mutating func reversedWords() -> String {
mutating не нужен

2019-11-09 14:11 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		//let reversedString = String(string.reversed())
лишняя закомментированная строка

2019-11-09 14:11 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		if result == "+" || result == "7" || result == "8" {
нет проверки на код страны

2019-11-11 09:58 UTC, ArtemPrivet requested changes

2019-11-11 09:58 UTC, ArtemPrivet commented on Homework2/Homework2Tests/CalculatorTests.swift
> +	private var string = "проверка ввода"
Зачем поменял на var?

2019-11-11 09:58 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +		let result = self.split(separator: " ").map { String($0.reversed()) }.joined(separator: " ")
Совет, такое лучше не писать в одну строку, а переносить 
self.split(separator: " ")
.map { String($0.reversed()) }
.joined(separator: " ")

2019-11-11 12:50 UTC, leningradspb commented on Homework2/Homework2Tests/CalculatorTests.swift
> +	private var string = "проверка ввода"
C let не билдилось(

2019-11-11 12:50 UTC, leningradspb commented on Homework2/Homework2/String+Extensions.swift
> +		let result = self.split(separator: " ").map { String($0.reversed()) }.joined(separator: " ")
Хорошо

2019-11-11 12:51 UTC, ArtemPrivet commented on Homework2/Homework2Tests/CalculatorTests.swift
> +	private var string = "проверка ввода"
Не может такого быть

2019-11-11 12:59 UTC, ArtemPrivet requested changes

2019-11-11 12:59 UTC, ArtemPrivet commented on Homework2/Homework2Tests/CalculatorTests.swift
> +	private var string = "проверка ввода"
У тебя не билдилось, потому что ты указал `mutating` для функции `reversedWords()`, нужно удалить этот префикс

2019-11-11 13:02 UTC, leningradspb commented on Homework2/Homework2Tests/CalculatorTests.swift
> +	private var string = "проверка ввода"
(facepalm)

2019-11-11 13:23 UTC, MisnikovRoman approved these changes

2019-11-11 13:30 UTC, ArtemPrivet approved these changes

2019-11-11 13:34 UTC, closed without merging