belov_anton/string_extension
ArtemPrivet/FocusStartHomeworks pull request #38
Opened 2019-11-09 08:59 UTC by belannik

2019-11-09 14:54 UTC, MisnikovRoman requested changes

2019-11-09 14:54 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		if characterArray[0] == "7" || characterArray[0] == "8" ||
Условие if'a можно перести в guard

2019-11-09 14:54 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +			let intArray = characterArray.compactMap{ Int(String($0)) }
тут логичнее использовать `.filter { $0.isNumber }`

2019-11-09 14:54 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +		var characterArray = [Character]()
лучше не использовать названия перменных с названиями типов. `characters` - оптимальный вариант

2019-11-09 20:07 UTC, MisnikovRoman approved these changes

2019-11-10 06:47 UTC, ArtemPrivet approved these changes

2019-11-10 06:47 UTC, closed without merging