rutsman_aleksandr/string_extension
ArtemPrivet/FocusStartHomeworks pull request #41
Opened 2019-11-09 09:00 UTC by svshkv

2019-11-09 14:59 UTC, MisnikovRoman requested changes
Нужно поправить замечания из предыдущего пула

2019-11-09 15:26 UTC, MisnikovRoman submitted a review, later dismissed

2019-11-10 06:45 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +		let reversedWordsArr = self
`reversedWords` было бы достаточно для названия переменной. 
Но это минор, можно не исправлять

2019-11-10 06:46 UTC, ArtemPrivet requested changes

2019-11-10 06:46 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +		let phoneTest = NSPredicate(format: "SELF MATCHES %@", regex)
`phoneTest` не корректрое название. Все таки это не тест. Давай назовем `phonePredicate`

2019-11-11 16:57 UTC, ArtemPrivet approved these changes

2019-11-12 04:54 UTC, MisnikovRoman approved these changes

2019-11-12 04:55 UTC, MisnikovRoman commented
✅ ДЗ2 принято

2019-11-12 04:55 UTC, closed without merging