khudzhamkulova_ekaterina/string_extension
ArtemPrivet/FocusStartHomeworks pull request #46
Opened 2019-11-09 09:06 UTC by K-Khud

2019-11-09 15:13 UTC, MisnikovRoman requested changes

2019-11-09 15:13 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +	}
нужно сделать автоформатирование кода `ctrl+I`

2019-11-09 15:13 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +	} while number.contains(" ") || number.contains("(") || number.contains(")") || number.contains("-")
весь этот код можно заменить на метод `.filter`

2019-11-09 15:13 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
> +	number.insert("?", at: number.startIndex)
А зачем ты вставляешь вопросительный знак? можно же сразу `return false`

2019-11-10 06:37 UTC, ArtemPrivet requested changes

2019-11-10 06:37 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +	for wordIndex in wordsArray.indices {
Я бы предложил тут использовать .enumerated(), код стал бы нагляднее

2019-11-10 06:37 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +	let wordsArray = self.components(separatedBy: " ")
Еще такой совет. Выносить все строковые константы в переменные. Это будет хорошей привычкой. Например, у тебя тут переиспользуется  сепаратор. Можно вынести его в переменную `let separator = " "`

2019-11-10 06:37 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +	if wordIndex < (wordsArray.count - 1) {
Минор, но можно было вместо `.count` написать `.endIndex`, логика бы не поменялась, но зато везде фигурировали бы индексы

2019-11-10 06:37 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +	print(result)
Принты мы не оставляем

2019-11-10 15:53 UTC, K-Khud commented on Homework2/Homework2/String+Extensions.swift
> +	print(result)
убрала, спасибо.

2019-11-10 15:53 UTC, K-Khud commented on Homework2/Homework2/String+Extensions.swift
> +	if wordIndex < (wordsArray.count - 1) {
заменила, спасибо.

2019-11-10 15:55 UTC, K-Khud commented on Homework2/Homework2/String+Extensions.swift
> +	let wordsArray = self.components(separatedBy: " ")
поняла, спасибо. есть ли такое, что нужно объявления констант выносить в начало файла?

2019-11-10 15:55 UTC, K-Khud commented on Homework2/Homework2/String+Extensions.swift
> +	for wordIndex in wordsArray.indices {
поняла, сделано.

2019-11-10 15:56 UTC, K-Khud commented on Homework2/Homework2/String+Extensions.swift
> +	number.insert("?", at: number.startIndex)
точно, спасибо.

2019-11-10 15:57 UTC, K-Khud commented on Homework2/Homework2/String+Extensions.swift
> +	} while number.contains(" ") || number.contains("(") || number.contains(")") || number.contains("-")
сделано, спасибо )

2019-11-10 16:21 UTC, ArtemPrivet requested changes

2019-11-10 16:21 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +		if self.contains(" ") {
Тут `" "` надо бы тоже наменить на `separator`

2019-11-10 16:21 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +					newString += " "
И тут бы заменить на `separator`

2019-11-10 16:21 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +			for (wordIndex, newWord)	in wordsArray.enumerated() {
Слишком большое расстояние перед `in`

2019-11-10 16:25 UTC, ArtemPrivet commented on Homework2/Homework2/String+Extensions.swift
> +	let wordsArray = self.components(separatedBy: " ")
Бывает что есть смысл выносить константы в начало файла. Но в данном случае такого делать не нужно

2019-11-10 18:40 UTC, ArtemPrivet approved these changes

2019-11-11 05:19 UTC, MisnikovRoman approved these changes

2019-11-11 05:19 UTC, MisnikovRoman commented
✅ ДЗ2 принято

2019-11-11 05:20 UTC, closed without merging