fedorov_kirill/test
ArtemPrivet/FocusStartHomeworks pull request #5
Opened 2019-10-30 17:50 UTC by ikirillfedorov

swiftlint fixes

2019-11-07 10:47 UTC, ArtemPrivet requested changes
Смотри, у тебя тут почему-то снова добавился swiftlint и из-за этого куча изменений
Ты создал новый проект, а надо было залить изменения в текущий. Посмотри как другие ребята сделали. Если будут вопросы, то пиши

2019-11-07 11:20 UTC, MisnikovRoman requested changes
Исправить дерево файлов

2019-11-07 12:20 UTC, MisnikovRoman reviewed
Как и сказал Артем нужно разобраться с деревом файлов

2019-11-07 17:42 UTC, MisnikovRoman approved these changes

2019-11-08 08:04 UTC, ArtemPrivet approved these changes

2019-11-08 08:07 UTC, closed without merging