shalashnikov_maxim/high_order_funсtions
ArtemPrivet/FocusStartHomeworks pull request #52
Opened 2019-11-12 16:26 UTC by b0sya

2019-11-12 16:44 UTC, MisnikovRoman requested changes

2019-11-12 16:44 UTC, MisnikovRoman commented on Homework2/Homework2/String+Extensions.swift
>  extension String
Заехали изменения из второго домашнего задания

2019-11-12 16:44 UTC, MisnikovRoman commented on Homework3/Homework3/Sequence+Extensions.swift
> +	 func customReduce<T>(_ initialResult: T, _ nextPartialResult: (T, Element) -> (T)) -> T {
Нужно выбрать один из двух вариантов либо ‘Self.Element’ либо ‘Element’

2019-11-12 16:44 UTC, MisnikovRoman commented on Homework3/Homework3/Sequence+Extensions.swift
> +		 for elem in self {
Всегда лучше использовать полные слова для названия переменных

2019-11-12 16:44 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private var string = "проверка ввода"
А зачем ты на ‘var’ поменял?

2019-11-12 16:44 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private func addSquareOfTheNext(_ num1: Int, _ num2: Int) -> Int {
Методы нигде не используются

2019-11-12 17:54 UTC, b0sya commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private var string = "проверка ввода"
Xcode потребовал

2019-11-12 20:48 UTC, MisnikovRoman commented
А теперь ты удаляешь 13 файлов из проекта 😢

2019-11-13 06:54 UTC, MisnikovRoman approved these changes
👌🏻

2019-11-13 08:06 UTC, ArtemPrivet approved these changes

2019-11-13 14:26 UTC, closed without merging