shelginskiy_igor/high_order_funсtions
ArtemPrivet/FocusStartHomeworks pull request #54
Opened 2019-11-12 16:59 UTC by Engwar

2019-11-12 18:09 UTC, MisnikovRoman requested changes

2019-11-12 18:09 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private func goToInt(_ stroka: String) -> Int? {
Переменные написанные транслитом лучше не использовать

2019-11-12 18:09 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> + 	private func squareSumm(summ: Int, digit: Int) -> Int {
sum пишется с одной m

2019-11-12 18:09 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private func stringWithSpaces(_ string1: String, _ string2: String) -> String {
Опять переменные с номерами лучше избегать. Тут можно взять пример у эппл и использовать названия left-right или first-second

2019-11-12 18:09 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private func someAscii(_ char: Character) -> UInt8? {
А почему some? У нас же вполне определенный ascii код символа

2019-11-12 18:09 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private func goToInt(_ stroka: String) -> Int? {
Название метода не соответствует действиям в теле. GoTo логичнее было бы использовать для переходов между экранами.

2019-11-12 18:27 UTC, Engwar commented
Постарался поправить названия на более логичные

2019-11-12 20:46 UTC, MisnikovRoman submitted a review, later dismissed

2019-11-12 20:46 UTC, MisnikovRoman commented on Homework3/Homework3/Sequence+Extensions.swift
> +		}
Минор: либо выражение с фигурными скобками на одной строке, либо на трёх.

2019-11-13 06:56 UTC, MisnikovRoman approved these changes
👍🏻

2019-11-13 08:18 UTC, ArtemPrivet approved these changes

2019-11-13 14:26 UTC, closed without merging