rustman_aleksandr/high_order_functions
ArtemPrivet/FocusStartHomeworks pull request #58
Opened 2019-11-13 08:44 UTC by svshkv

2019-11-13 14:35 UTC, MisnikovRoman requested changes

2019-11-13 14:35 UTC, MisnikovRoman commented on Homework3/Homework3/Sequence+Extensions.swift
> +		for el in self {
Давай будем использовать полное название переменной

2019-11-13 14:35 UTC, MisnikovRoman commented on Homework3/Homework3/Sequence+Extensions.swift
> +		for el in self {
и тут

2019-11-13 14:35 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +		let expectedStrings = strings.reduce(" ", addSpaceBetween)
менять начальное значение не стоило

2019-11-13 14:38 UTC, ArtemPrivet requested changes

2019-11-13 14:38 UTC, ArtemPrivet commented on Homework3/Homework3/Sequence+Extensions.swift
> +		for el in self {
Нет смысла сокращать названия, лучше написать `element`

2019-11-13 14:38 UTC, ArtemPrivet commented on Homework3/Homework3/Sequence+Extensions.swift
> +		for el in self {
Тут тоже лучше `element`

2019-11-14 08:30 UTC, ArtemPrivet approved these changes

2019-11-14 08:33 UTC, MisnikovRoman approved these changes

2019-11-14 08:33 UTC, closed without merging