khudzhamkulova_ekaterina/high_order_functions
ArtemPrivet/FocusStartHomeworks pull request #60
Opened 2019-11-13 14:54 UTC by K-Khud

2019-11-13 15:06 UTC, ArtemPrivet requested changes

2019-11-13 15:06 UTC, ArtemPrivet commented on Homework3/Homework3/Sequence+Extensions.swift
> +			if let unwrapped = customFunction(element) {
Смотри, в `where` ты фильтруешь значения вызывая клоужер, а потом опять же вызываешь этот клоужер для анврапа.  `where` тут не нужен, ибо if let и так делает эту же фильтрацию

2019-11-13 15:06 UTC, MisnikovRoman requested changes

2019-11-13 15:06 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +		let expectedNumbers = numbers.reduce(0) { toModifyArray($0, $1) }
нужно сделать так как в методах .customMap(), где название функции (например, square) находится в аргументах

2019-11-13 15:06 UTC, MisnikovRoman commented on Homework3/Homework3Tests/Homework3Tests.swift
> +	private func toModifyArray(_ firstNumber: Int, _ secondNumber: Int) -> Int {
логичнее было бы назвать метод просто toArray, тогда бы вызов метода reduce читался отлично: strings.reduce(0, toArray)

2019-11-13 15:21 UTC, K-Khud commented on Homework3/Homework3/Sequence+Extensions.swift
> +			if let unwrapped = customFunction(element) {
да, но если убрать where, swiftLint вывешивает предупреждение "For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)"

2019-11-13 15:57 UTC, ArtemPrivet commented on Homework3/Homework3/Sequence+Extensions.swift
> +			if let unwrapped = customFunction(element) {
Понял, тогда вопросов больше нет

2019-11-13 15:58 UTC, ArtemPrivet approved these changes

2019-11-14 08:32 UTC, MisnikovRoman approved these changes

2019-11-14 08:32 UTC, closed without merging