WIP: khudzhamkulova_ekaterina/calculator
ArtemPrivet/FocusStartHomeworks pull request #67
Opened 2019-11-19 18:03 UTC by K-Khud

Не получается разобраться, где должен считаться размер кнопок, в дебаггере при распечатке описания frame = (0 0; 0 0). Может, стеквью неправильно настраиваю.

2019-11-19 18:39 UTC, ArtemPrivet commented on Calculator/Calculator/Views/CalculatorButton.swift
> +		addSubview(button)
Смотри, ты добавила сабью, а констреинты не добавила

2019-11-19 18:41 UTC, ArtemPrivet commented on Calculator/Calculator/Views/CalculatorButton.swift
> +final class CalculatorButton: UIView
И вообще, это подло называть класс `Button`, когда это вью. И ты уверена что тебе нужен этот класс, а базовой кнопку тебе будет недостаточно?

2019-11-19 18:53 UTC, ArtemPrivet commented on Calculator/Calculator/Views/ButtonRow.swift
> +		let rowStack = UIStackView(arrangedSubviews: rowOfButton)
Вот еще обрати внимание на этот момент. У тебя в StackView добавится 1 кнопка, а не 4, хотя массив у нас содержит 4 элемента

2019-11-19 18:54 UTC, ArtemPrivet requested changes
Пройдить по вьюшкам и посмотри, что везде где надо добавлены констрейнты. И возможно иерархию вью можно сделать попроще. Чем больше вложенность вьюх тем больше проблем

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorButton.swift
> +final class CalculatorButton: UIView
согласен, думаю тут нужно было наследоваться от UIButton, тогда и констрейнты не нужны будут

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +			rowOfButton.append(button)
тут ты добавляешь в массив одну и ту же кнопку, а нужно создавать отдельные экземпляры класса CalculatorButton

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +		rowStack.distribution = .fill
лучше fillEqual, кнопки же все одинаковые

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +final class ButtonRow: UIView
опять же просто вью, а по сути тут стекВью

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +		translatesAutoresizingMaskIntoConstraints = false
ты опять не задаешь значения констрейнтов стека относительно родительской вью

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +		addSubview(rowStack)
ты нигде не добавляешь компоненты в стек вью, для этого есть специальный метод addArrangedSubview(_:)

2019-11-19 18:56 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonsStack.swift
> +			mainStack.addArrangedSubview(row)
а в этом классе у тебя двойной стек (класс ButtonsStack отнаследованный от UIStackView и mainStackView)

2019-11-19 19:12 UTC, MisnikovRoman commented
ну и вообще советую постепенно проверять сделанное. т.е. сразу как ты сделала CalculatorButton, создаешь экземпляр во VC и проверяешь, что все работает. Потом тоже самое со стеком из 4х кнопок и т.д.

2019-11-19 19:13 UTC, K-Khud commented on Calculator/Calculator/Views/CalculatorButton.swift
> +		addSubview(button)
Исправила

2019-11-19 19:14 UTC, K-Khud commented on Calculator/Calculator/Views/CalculatorButton.swift
> +final class CalculatorButton: UIView
Исправила наследование и добавила констрейнты, но кнопки не появляются

2019-11-19 19:17 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +	let rowStack = UIStackView()
тут видимо stackView теперь не нужен, ты же можешь вызывать методы у self

2019-11-19 19:17 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonRow.swift
> +				rowStack.leadingAnchor.constraint(equalTo: self.safeAreaLayoutGuide.leadingAnchor, constant: 0),
это же вложенная вью, тут не нужна safearea

2019-11-19 19:17 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorButton.swift
> +	private static var indentifierFactory = 0
переменная фабрика? интересный нейминг

2019-11-19 19:17 UTC, K-Khud commented on Calculator/Calculator/Views/ButtonRow.swift
> +		let rowStack = UIStackView(arrangedSubviews: rowOfButton)
Исправила, избавилась от массива, чтобы кнопки сразу в стек шли.

2019-11-19 19:41 UTC, K-Khud commented on Calculator/Calculator/Views/ButtonRow.swift
> +	let rowStack = UIStackView()
заменила везде, где можно на self, кнопки появились, конфликты констрейнтов исчезли. вау

2019-11-20 21:23 UTC, K-Khud commented on Calculator/Calculator/Views/ButtonRow.swift
> +				rowStack.leadingAnchor.constraint(equalTo: self.safeAreaLayoutGuide.leadingAnchor, constant: 0),
Исправила

2019-12-03 12:19 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:19 UTC, closed without merging