kozlov_stanislav/calculator
ArtemPrivet/FocusStartHomeworks pull request #70
Opened 2019-11-19 20:55 UTC by artbleymy

Реализация калькулятора, была не была

2019-11-20 12:42 UTC, ArtemPrivet requested changes
И еще ,у тебя можно ввести бесконечное колличество нулей подряд. 
И надо хоть как-то ограничить ввод максимального числа

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Application/AppDelegate.swift
> +		}
Тут можно было без If let обойтись.
Работать с `window` через `window?.root...`

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +		let button = UIButton(frame: .zero)
UIButton()

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/Calculations.swift
> +		if let operation = operations[symbol] {
guard

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +		let button = UIButton(frame: .zero)
UIButton()

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +			])
Если констреинт 1, то можно в 1 строчку написать 
`button.heightAnchor.constraint(equalTo: button.widthAnchor, multiplier: 1).isActive = true`

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +	}
Функция нигде не используется

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var resultLabel = UILabel()
Создаешь тут Label, а потом его заменяешь на другой, вместо того, чтобы просто задать ему свойства. Тогда и `var` не понадобится

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private let buttonTitles = [
А этот массив можно было отсюда убрать в ButtonCreator?

2019-11-20 12:42 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +			return createNumberButton(with: title)
Все таки это numberButton или digitButton?

2019-11-20 15:18 UTC, artbleymy commented
Поправил по замечаниям, + в нескольких местах еще заменил if let на guard

2019-11-22 12:57 UTC, ArtemPrivet requested changes

2019-11-22 12:57 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +		buttonTitles.forEach{ buttons.append( createButton(title: $0)) }
Как альтернативу тут можно было бы использовать функцию `map`
let buttons = buttonTitles.map { createButton(title:$0) }

2019-11-22 12:57 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/ButtonCreator.swift
> +		hexToggleTitleColor: String?)] =
Давай для всех этих свойств создадим отдельную структуру

2019-11-22 16:01 UTC, artbleymy commented
Поправил по замечаниям

2019-12-03 12:39 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:39 UTC, closed without merging