WIP: medvedev_ivan/calculator
ArtemPrivet/FocusStartHomeworks pull request #73
Opened 2019-11-21 14:28 UTC by Med1D

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.getView()?.delegate = self
тут логичнее было бы сделать вычисляемую переменную
``` swift 
var calculatorView: CalculatorView? {
    return self.view as? CalculatorView
}
```

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.polandItems.removeAll()
Лучше вынести работу с `[PolandItem]` в отдельную сущность (например, CalculatorLogic или CalculatorEngine)

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.polandItems.removeAll()
А то ты начинаешь смешить бизнес-логику (вычисление операций) и работу с UI (обновление лэйблов)

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Models/PolandItem.swift
> +enum PolandItem
А почему польский элемент? Это же просто компонент массива, который может быть записан в стандартной форме и в обратной польской нотации

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Models/PolandItem.swift
> +func polandScript(input array: [PolandItem]) -> [PolandItem] {
соответственно метод должен называться как-то так:` func  convertToReversePolishNotation(_ items: Item)`

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Models/PolandItem.swift
> +func polandScript(input array: [PolandItem]) -> [PolandItem] {
Плюс метод должен входить в какой-нибудь класс(структуру). Не должно быть отдельно висящих метод доступных во всем проекте

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Models/PolandItem.swift
> +func polandScriptGetResult(input array: [String]) -> Double? {
Слишком много методов, которые начинаются с polandScript. Это звоночек, что нужно объединять их в методы одной сущности

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.polandItems.removeAll()
Плюс можно будет написать тесты на работу логики калькулятора.

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +		for index in 0 ..< 19 {
19 можно вынести в отдельную переменную

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +			buttons[0].trailingAnchor.constraint(equalTo: buttons[1].leadingAnchor, constant: -14),
14 как и другие числовые константы лучше вынести в отдельный enum с константами

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +	@objc func clickedButton(sender: UIButton) {
Обработчик нажатий лучше делать не во вью, а в контроллере как минимум

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +			break
сюда бы ассерт не помешал

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +	@objc func clickedButton(sender: UIButton) {
Как один из вариантов - хранить переменную с замыканием
``` swift 
var tapHandler: ((String) -> Void)?
```
а код замыкания задавать в VC

2019-11-22 09:23 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +	@objc func clickedButton(sender: UIButton) {
Или использовать паттерн делегирования, но с правильным неймингом - `CalculatorViewDelegate` вместо `CalculatorActionsProtocol`. Плюс у делегата должен быть метод по типу такого  - `func clickedButton(withText text: String)`. А вот уже что делать должен решать контроллер и перенаправлять действия в `CalculatorEngine`

2019-11-22 17:20 UTC, Med1D commented on Calculator/Calculator/Views/CalculatorView.swift
> +			break
fixed

2019-11-22 17:20 UTC, Med1D commented on Calculator/Calculator/Views/CalculatorView.swift
> +			buttons[0].trailingAnchor.constraint(equalTo: buttons[1].leadingAnchor, constant: -14),
fixed

2019-11-22 17:20 UTC, Med1D commented on Calculator/Calculator/Views/CalculatorView.swift
> +		for index in 0 ..< 19 {
fixed

2019-11-22 17:35 UTC, Med1D commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.getView()?.delegate = self
fixed

2019-11-22 18:43 UTC, Med1D commented on Calculator/Calculator/Views/CalculatorView.swift
> +	@objc func clickedButton(sender: UIButton) {
fixed

2019-11-22 19:50 UTC, Med1D commented on Calculator/Calculator/Models/PolandItem.swift
> +func polandScript(input array: [PolandItem]) -> [PolandItem] {
fixed

2019-11-22 19:50 UTC, Med1D commented on Calculator/Calculator/Models/PolandItem.swift
> +enum PolandItem
fixed

2019-11-22 19:51 UTC, Med1D commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.polandItems.removeAll()
fixed

2019-11-22 19:51 UTC, Med1D commented on Calculator/Calculator/Models/PolandItem.swift
> +func polandScript(input array: [PolandItem]) -> [PolandItem] {
fixed

2019-11-22 19:51 UTC, Med1D commented on Calculator/Calculator/Models/PolandItem.swift
> +func polandScriptGetResult(input array: [String]) -> Double? {
fixed

2019-11-23 14:12 UTC, MisnikovRoman requested changes
UI:
- Размер шрифта на цифровых кнопках не соответствует дизайну
- Знаки операций тоже не соответствую дизайну

Математика:
- Не работает отрицание для результата операции ("1,+,1,=,+/-")
- Неправильный результат умножения больших чисел (999999999*999999999)
- Неправильный результат 1+2/3
- Не работает 20---3

Архитектура:
- Вынести приватные функции в отдельный extension
- Реализация протокола делегирования в отдельных extension
- Лишние методы в протоколе CalculatorViewDelegate
- Все еще нет отдельной сущности с логикой вычислений

Тесты:
- self-ы в тестах
- Разные результаты в 1+3/2 в тестах и в приложении

2019-11-23 14:12 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +final class CalculatorViewController: UIViewController, CalculatorViewDelegate
Реализацию протокола `CalculatorViewDelegate` вынести в отдельный extension

2019-11-23 14:12 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	}
Всегда нужно стараться не использовать кастинг типов где это возможно, особенно тут. Достаточно просто создать переменную:
``` swift
private let calculatorView = CalculatorView()
```
И использовать ее в методе `loadView()`

2019-11-23 14:12 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.polandItems.removeAll()
🤔 методы percent, comma, equal и прочие все еще во VC

2019-11-23 14:12 UTC, MisnikovRoman commented on Calculator/Calculator/Protocols/CalculatorViewDelegate.swift
> +	func allClear()
Этот и следующий методы не используются в CalculatorView

2019-11-23 14:12 UTC, MisnikovRoman commented on Calculator/CalculatorTests/CalculatorTests.swift
> +	func testDivide() {
Тесты это прикольно но то, что они не совпадают с реальностью - проблема
Если добавить такой тест
``` swift
func testTwoOperations() {
  let items: [Item] = [.number(1), .sign(.plus), .number(3), .sign(.divide), .number(2)]
  let expectedResult = 2.5
  guard let resultItems = polishNotation.makeCalculation(items) else {
    XCTFail("Отсутствует результат")
    return
  }
  XCTAssertEqual(resultItems, expectedResult)
}
```
то он пройдет (ответ 2.5), но если сделать тоже самое в калькуляторе - результат будет другой (2)

2019-11-29 22:18 UTC, Med1D commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +final class CalculatorViewController: UIViewController, CalculatorViewDelegate
fixed

2019-11-29 22:18 UTC, Med1D commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	}
fixed

2019-12-01 17:37 UTC, Med1D commented
![6gGLqaT30sw](https://user-images.githubusercontent.com/32410337/69917738-4be3b000-147a-11ea-8454-a12b98b06557.jpg)

2019-12-03 12:39 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:39 UTC, closed without merging