shalashnikov_maxim/calculator
ArtemPrivet/FocusStartHomeworks pull request #75
Opened 2019-11-22 15:34 UTC by b0sya

Писал логику в режиме "О, еще одна скрытая фича!", поэтому получилось, по моему, не очень

2019-11-23 17:00 UTC, ArtemPrivet requested changes

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/View/CalculatorButton.swift
> +	//не забыть исправить
Не забыл? 😁

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		}
Смотри, а если бы у нас приложение было бы мультиязычным? Тогда пришлось бы все варианты перечислять. 
Давай будем передавать value как String?, и если он у нас nil, то выводить "Ошибка"

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			if button.identifier == nil {
Хм, у тебя есть отличный enum ButtonType. Давай сделаем такое свойство у кнопки и будем уже его проверять, а не сравнивать `button.identifier` с `nil`

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if operatorWasUsed == false {
Guard, избавимся от вложености

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		let clearResultLabelText = resultLabelText.filter("+0123456789.".contains)
А почему тут +?

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard clearResultLabelText.count < 9 || operatorWasUsed == true else  { return }
`9` надо бы вынести в константу, а то не понятно что эта цифра значит

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if fixedValue.contains(",") == false && fixedValue != "-0" && fixedValue != "Ошибка" {
Очень много вижу слово "Ошибка", есл изавтра скажут отображать что-то другое, то придется во многих местах менять, давай тоже вынесем в переменную

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				print(expression)
Принты удаляем

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if canDeleteOnlySeconInput == true {
`Second`

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let oper = sender.identifier else { return }
А почему `oper` а не `operation`?

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		print(expression)
Удаляем принты

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if calculator.isOperator(symbol: value) == false {
Это тоже можно в guard

2019-11-23 17:00 UTC, ArtemPrivet commented on Calculator/Calculator/Services/TypeOfButton.swift
> +	case symbolic
А не думал сделать enum со связанным значением?

2019-11-23 18:22 UTC, b0sya commented on Calculator/Calculator/View/CalculatorButton.swift
> +	//не забыть исправить
Не помню :)

2019-11-23 19:25 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			if button.identifier == nil {
Fixed

2019-11-23 19:25 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if operatorWasUsed == false {
Fixed

2019-11-23 19:25 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		let clearResultLabelText = resultLabelText.filter("+0123456789.".contains)
Fixed

2019-11-23 19:25 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard clearResultLabelText.count < 9 || operatorWasUsed == true else  { return }
fixed

2019-11-23 19:25 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if fixedValue.contains(",") == false && fixedValue != "-0" && fixedValue != "Ошибка" {
fixed

2019-11-23 19:26 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				print(expression)
fixed

2019-11-23 19:26 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if canDeleteOnlySeconInput == true {
Fixed

2019-11-23 19:26 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let oper = sender.identifier else { return }
Fixed (почему то раньше "operation" выделялся красным, как что то зарезервированное Свифтом)

2019-11-23 19:26 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		print(expression)
Fixed

2019-11-23 19:26 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		if calculator.isOperator(symbol: value) == false {
Fixed

2019-11-23 21:31 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let oper = sender.identifier else { return }
можно было использовать так `operation`

2019-11-23 22:34 UTC, MisnikovRoman requested changes
В целом неплохо, но фаталерроры конечно портят впечатление. Плюс еще заметил, что из-за того что не отключена горизонтальная ориентация можно получить такое:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-24 at 01 24 49](https://user-images.githubusercontent.com/36447757/69486215-7a4e0380-0e5a-11ea-9500-8788821bb89e.png)

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			return String(Int(value))
Fatal error если value > Int.max

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
>  final class CalculatorViewController: UIViewController
Минор: но большие числа выглядят на экране странно
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-24 at 00 39 02](https://user-images.githubusercontent.com/36447757/69485659-a31eca80-0e53-11ea-87d3-b69f6f787dda.png)

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			if button.identifier == nil {
пока не fixed 😕

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var isGetingResult = false
getting

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Extensions/StringExtension.swift
> +	func count(character: Character) -> Int {
правильнее было бы назвать `func count(of character: Character) -> Int`

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Extensions/StringExtension.swift
> +import Foundation
Минор: тут бы новая строка не помешала

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +	//Получения польской нотации
Лучше вместо коммента назвать было метод toReversePolishNotation

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +	func toRPN(inputArray: [String]) -> [String] {
метод локальный можно сделать private

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +			return 3
Как раз для того чтобы не использовать не понятные числа, были придуманы перечисления 😉

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +			switch getOperatorPriority(calcOperator: item) {
лучше использовать полные слова в названиях аргументов и переменных

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +					}
Лучше заменить на guard

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +	//Расчет выражения
Если из названия метода понятно чем он занимается, то комментарий надо убирать. А если нужно сделать пояснения по работе метода, то лучше использовать документирование через тройной слэш

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +		switch oper {//И производим над ними действие, согласно оператору
Как по мне, комментарий бесполезен

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Calculator.swift
> +			//result = leftOperand - (leftOperand * rightOperand) / 100
Удоли

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/Stack.swift
> +	var peek: T? { return array.first }
насколько я помню, через peek смотрят последний элемент в стеке

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/View/CalculatorButton.swift
> +	private func chooseTypeAndCreate(of type: TypeOfButton, with title: String) {
исходя из названия метода у тебя должно быть возвращаемое значение (Create)

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/View/CalculatorView.swift
> +			button.layoutIfNeeded()
А зачем принудительно вызвать обновление лейаута?

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/View/CalculatorView.swift
> +	private func createButton(title: String) -> CalculatorButton {
лучше `func createButton(withTitle title: String) -> ...`

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Services/TypeOfButton.swift
> +enum TypeOfButton
Можно просто `ButtonType`

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/View/CalculatorView.swift
> +			//stackView.translatesAutoresizingMaskIntoConstraints = false
Удалить

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/CalculatorTests/Info.plist
> -	<key>CFBundleVersion</key>
🤔 а это зачем?

2019-11-23 22:34 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				expression.removeLast()
Тут fatalError при нажитии на кнопку "+/-" если на экране надпись "Ошибка"

2019-11-23 23:37 UTC, b0sya commented on Calculator/CalculatorTests/Info.plist
> -	<key>CFBundleVersion</key>
Что это такое?

2019-11-23 23:39 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			if button.identifier == nil {
Не запушился коммит, прошу прощения

2019-11-24 11:42 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +	func toRPN(inputArray: [String]) -> [String] {
А как тестировать приватные методы?

2019-11-24 13:10 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +					}
Мне же не нужно завершать метод если это условие не выполнилось, необходимо просто пропустить итерацию

2019-11-24 13:32 UTC, b0sya commented on Calculator/Calculator/Services/TypeOfButton.swift
> +enum TypeOfButton
ButtonType уже занять UIButton

2019-11-24 13:43 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			return String(Int(value))
fixed

2019-11-24 13:43 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
>  final class CalculatorViewController: UIViewController
fixed

2019-11-24 13:43 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var isGetingResult = false
fixed

2019-11-24 13:43 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +	//Получения польской нотации
fixed

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +			return 3
fixed

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +			switch getOperatorPriority(calcOperator: item) {
fixed

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +	//Расчет выражения
fixed

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +		switch oper {//И производим над ними действие, согласно оператору
fixed

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/Services/Calculator.swift
> +			//result = leftOperand - (leftOperand * rightOperand) / 100
fixed

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/Services/Stack.swift
> +	var peek: T? { return array.first }
Да, действительно. Исправил

2019-11-24 13:44 UTC, b0sya commented on Calculator/Calculator/View/CalculatorButton.swift
> +	private func chooseTypeAndCreate(of type: TypeOfButton, with title: String) {
fixed

2019-11-24 13:45 UTC, b0sya commented on Calculator/Calculator/View/CalculatorView.swift
> +			button.layoutIfNeeded()
На stackOverflow прочитал что могут быть проблемы с размерами без этой строки. Но тут и без этого все ок, убрал

2019-11-24 13:45 UTC, b0sya commented on Calculator/Calculator/View/CalculatorView.swift
> +	private func createButton(title: String) -> CalculatorButton {
fixed

2019-11-24 13:45 UTC, b0sya commented on Calculator/Calculator/View/CalculatorView.swift
> +			//stackView.translatesAutoresizingMaskIntoConstraints = false
fixed

2019-11-24 13:45 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				expression.removeLast()
fixed

2019-11-24 13:49 UTC, b0sya commented on Calculator/Calculator/Extensions/StringExtension.swift
> +	func count(character: Character) -> Int {
fixed

2019-11-24 14:27 UTC, b0sya commented on Calculator/Calculator/View/CalculatorButton.swift
> +	//не забыть исправить
fixed

2019-11-24 14:27 UTC, b0sya commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		}
fixed

2019-11-24 14:28 UTC, b0sya commented on Calculator/Calculator/Services/TypeOfButton.swift
> +	case symbolic
Вроде fixed

2019-12-03 12:38 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:38 UTC, closed without merging