shelginskiy_igor/calculator
ArtemPrivet/FocusStartHomeworks pull request #76
Opened 2019-11-22 20:32 UTC by Engwar

2019-11-24 11:30 UTC, MisnikovRoman requested changes
- Нет ограничения на ввод данных, при умножении 999999999 * 9999999999 - странный результат
- Неправильно расставлены констрейнты - ошибки в консоли 
- Нужно было отключить возможность  переверота устройства
- Разделение на сотни происходит только для результата, не работает при вводе длинных чисел

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
А вот этого тут быть точно не должно. Мы договорились поддерживать ось начиная от 10-ой

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Screen/CalculatorScreen.swift
> +final class CalculatorScreen: UIView
Логичней было бы перенести в папку к остальным view

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	var displayValue: Double? {
Все эти свойства используются только внутри VC - нужно было сделать их `private`

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			changeACButton()
Сложную логику для геттера и сеттера логичнее было бы вынести в отдельные методы

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.view.addGestureRecognizer(rightSwipe)
Раз уж начал выносить логику в отдельные методы, значит с GestureRecognizer'ами нужно поступать также

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	@objc func swipToDeleteNumber(_ sender: UISwipeGestureRecognizer) {
swipe

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Screen/CalculatorScreen.swift
> +			maker.bottom.equalTo(buttonsView.snp.top).offset(-8)
Числовые константы лучше выносить в отдельное перечисление
``` swift
enum Metrics {
  static let buttonsSpace: CGFloat = 16
  // ...
}
```

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/SupportingFiles/Assets.xcassets/operat.imageset/Contents.json
> +      "filename" : "Screen Shot 2019-11-22 at 22.57.20.png",
Для файлов тоже нужно использовать значащие имена

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ResultLabel.swift
> +
лишняя новая строка

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/StackButtons.swift
> +		translatesAutoresizingMaskIntoConstraints = false
Настройки в отдельные приватные методы

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/StackButtons.swift
> +	func addButtonsToArray() {
Название метода не соответствует процессам внутри

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/StackButtons.swift
> +			stack.spacing = 10
Опять же настройки нужно выносить в отдельные методы

2019-11-24 11:30 UTC, MisnikovRoman commented on install_swiftlint.sh
> +SWIFTLINT_PKG_URL="https://github.com/realm/SwiftLint/releases/download/0.37.0/SwiftLint.pkg"
Странно что эти изменения здесь присутствуют, они же есть в master ветке основного проекта? 🤔 
А ты делал мердж master ветки в свою?

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var brain = LogicOperation()
Переменная и класс называются абсолютно по-разному

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Brain/LogicOperations.swift
> +	private var pendingContainer = Double()
А почему ты просто не пишешь `private var pendingContainer = 0.0`?
Дальше в коде тоже нужно заменил инициализацию Double на `= 0.0`

2019-11-24 11:30 UTC, MisnikovRoman commented on Calculator/Calculator/Brain/LogicOperations.swift
> +		"%": Operation.percentOperation({ $0 / 100 }, { $0 / 100 * $1 }),
Мне кажется, что вычисление процента можно было сделать проще

2019-11-24 15:35 UTC, Engwar commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
исправил

2019-11-24 15:35 UTC, Engwar commented on Calculator/Calculator/Screen/CalculatorScreen.swift
> +final class CalculatorScreen: UIView
исправил

2019-11-24 15:35 UTC, Engwar commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	var displayValue: Double? {
исправил

2019-11-24 15:35 UTC, Engwar commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			changeACButton()
сделал

2019-11-24 16:18 UTC, Engwar commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.view.addGestureRecognizer(rightSwipe)
сделал

2019-11-24 16:21 UTC, Engwar commented on Calculator/Calculator/Views/StackButtons.swift
> +			stack.spacing = 10
сделал

2019-11-24 16:24 UTC, Engwar commented on install_swiftlint.sh
> +SWIFTLINT_PKG_URL="https://github.com/realm/SwiftLint/releases/download/0.37.0/SwiftLint.pkg"
я напутал когда создавал ветку  WIP вместо пулреквеста WIP. В итоге не заметил и продолжил работать в ветке WIP и отправлять в нее комиты, когда захотел все исправить то перемудрил с Fork. в Итоге скорее всего сделал так как не нужно, теперь и не вспомню ...

2019-11-24 16:25 UTC, Engwar commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var brain = LogicOperation()
исправил

2019-11-24 16:28 UTC, Engwar commented on Calculator/Calculator/Brain/LogicOperations.swift
> +	private var pendingContainer = Double()
исправил

2019-12-03 12:11 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:11 UTC, closed without merging