grigoryanc_arkadiy/calculator
ArtemPrivet/FocusStartHomeworks pull request #77
Opened 2019-11-22 21:07 UTC by FlightyNEO

2019-11-26 11:53 UTC, MisnikovRoman requested changes
В целом, все отлично, но есть небольшие недочеты

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.types.reduce(into: [[ButtonView?]]()) { matrixResult, rowOfType in
а почему reduce? ты из одного двухмерного массива получаешь другой, логично использовать `map`

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var countOfColumns: Int { buttons[0].count }
Безопаснее использовать `buttons.first.count ?? 0`

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +
Лишняя новая строка

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +
Еще одна

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			maker.height.equalTo(113)
Все константы значений для констрейнтов можно был вынести в отдельный enum

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +extension CalculatorViewController
Чтобы не писать у всех метод ниже `private` модификатор доступа можно добавить ко всему extension'у

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		var countOfDigits: Int {
а почему эта и следующие переменные вычисляемые? выгдядит так как будто можно использовать обычную переменную

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	/// - case percentOperation - (унарная операцияб бинарная операция)
операцияб

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	/// - case equals - операция "равно"
если честно, из такого описания сложно что-то понять не залезая в подробности реализации

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +			switch (lastOperation, newOperation) {
`lastOperation` не нужон

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +			// В стэке послдний элемент - операнд
послдний

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	mutating func performOperation(with symbol: Operator, completion: ((Response) -> Void)? = nil) {
мне кажется, можно было еще декомпозировать этот метод, но эт минор

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	// swiftlint:disable:next function_body_length
такое себе решение

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	// swiftlint:enable cyclomatic_complexity
а это зачем?

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	// MARK: ... Private metods
А зачем 3 точки перед текстом?

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/ConverterInfixToPostfixNotation.swift
> +//  ConverterInfixToPostfixNotation.swift
Конвертер? Название файла обычно подразумевает наличие сущности с таким же названием

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/ConverterInfixToPostfixNotation.swift
> +		case background(ButtonView.`Type`)
мне кажется, что не совсем верно добавлять ассоциированное значением с типом вьюхи к цвету. тут скорее должна быть обратная зависимость. вью должна знать о цвете

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/InfixToPostfixConverter.swift
> +enum InfixToPostfixConverter
эмм 🤔 еще один файл с конвертером

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Models/InfixToPostfixConverter.swift
> +		func popImfixToPostfixNotation() {
imfix

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/SupportingFiles/AppSetting.swift
> +
лишняя новая строка

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/SupportingFiles/AppSetting.swift
> +//		static let equals = #imageLiteral(resourceName: "divide")
удалить комментарии

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/SupportingFiles/CalculatorEngine.OperationStack+Equatable.swift
> +//  CalculatorEngine.OperationStack+Equatable.swift
Можно было определить в том же файле где и `CalculatorEngine`

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/SupportingFiles/CalculatorEngine.OperationStack+Initialization.swift
> +//  CalculatorEngine.OperationStack+Initialization.swift
это расширение тоже

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/SupportingFiles/UIColor+Adjust.swift
> +
энтер лишний

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonView.swift
> +		}
лучше вынести в отдельный метод

2019-11-26 11:53 UTC, MisnikovRoman commented on Calculator/CalculatorTests/CalculatorPercentTest.swift
> +	func test1() {
мне кажется нейминг тут дал сбой. у тебя переменная `one` не используется в `test1`, а используется в `test3`

2019-11-26 14:30 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.types.reduce(into: [[ButtonView?]]()) { matrixResult, rowOfType in
действительно )
fix

2019-11-26 14:30 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private var countOfColumns: Int { buttons[0].count }
fix

2019-11-26 14:30 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +
fix

2019-11-26 14:31 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +
fix

2019-11-26 14:33 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			maker.height.equalTo(113)
fix

2019-11-26 14:34 UTC, FlightyNEO commented on Calculator/Calculator/SupportingFiles/CalculatorEngine.OperationStack+Equatable.swift
> +//  CalculatorEngine.OperationStack+Equatable.swift
Старался уложиться в 400 свифтлинтовских строк )
fix

2019-11-26 14:34 UTC, FlightyNEO commented on Calculator/Calculator/SupportingFiles/CalculatorEngine.OperationStack+Initialization.swift
> +//  CalculatorEngine.OperationStack+Initialization.swift
fix

2019-11-26 14:34 UTC, FlightyNEO commented on Calculator/Calculator/SupportingFiles/UIColor+Adjust.swift
> +
fix

2019-11-26 14:34 UTC, FlightyNEO commented on Calculator/Calculator/Views/ButtonView.swift
> +		}
fix

2019-11-26 14:35 UTC, FlightyNEO commented on Calculator/CalculatorTests/CalculatorPercentTest.swift
> +	func test1() {
исправил нэйминги констант как в др. классах тестов
fix

2019-11-26 16:55 UTC, FlightyNEO commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	// MARK: ... Private metods
В минимапе на xCode 11 понятно выглядит ( и в списке разворачивающемся сверху)
Я обычно внутри модуля ... ставлю, а между модулями «-» ставлю. Так мне кажется нагляднее.

2019-11-26 20:04 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		var countOfDigits: Int {
потому-то они используются только в блоке if, а я хотел их вынести выше чтобы разгрузить блок if. И что бы они не высчитывались каждый раз, они вычисляемые.

2019-11-26 20:12 UTC, FlightyNEO commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	// swiftlint:enable cyclomatic_complexity
забыл убрать
fix

2019-11-26 20:14 UTC, FlightyNEO commented on Calculator/Calculator/Models/ConverterInfixToPostfixNotation.swift
> +//  ConverterInfixToPostfixNotation.swift
перепутал название файла
fix

2019-11-26 20:15 UTC, FlightyNEO commented on Calculator/Calculator/Models/InfixToPostfixConverter.swift
> +		func popImfixToPostfixNotation() {
fix

2019-11-26 20:15 UTC, FlightyNEO commented on Calculator/Calculator/SupportingFiles/AppSetting.swift
> +
fix

2019-11-26 20:15 UTC, FlightyNEO commented on Calculator/Calculator/SupportingFiles/AppSetting.swift
> +//		static let equals = #imageLiteral(resourceName: "divide")
fix

2019-11-26 20:16 UTC, FlightyNEO commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +			// В стэке послдний элемент - операнд
fix

2019-11-26 20:18 UTC, FlightyNEO commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +			switch (lastOperation, newOperation) {
да по логике получилось что в стоке только бинарные операции, поэтому проверять последний оператор не нужно.
fix

2019-11-26 20:18 UTC, FlightyNEO commented on Calculator/Calculator/Models/CalculatorEngine.swift
> +	/// - case percentOperation - (унарная операцияб бинарная операция)
fix

2019-11-26 20:19 UTC, FlightyNEO commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +extension CalculatorViewController
fix

2019-12-03 12:08 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:08 UTC, closed without merging