fedorov_kirill/calculator
ArtemPrivet/FocusStartHomeworks pull request #78
Opened 2019-11-22 21:57 UTC by ikirillfedorov

![Screenshot 2019-11-23 at 00 55 53](https://user-images.githubusercontent.com/45234669/69463225-2d036080-0d8c-11ea-93ed-8ea816cf152f.png)

2019-11-25 15:34 UTC, ArtemPrivet requested changes

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/CalculatorButtons.swift
> +	private func setButtonsColor() {
Почему `setButtonsColor` вызываешь из layoutSubviews?

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/CalculatorButtons.swift
> +			switch self.tag {
Использовать тэги лучше в крайнем случае. Предлагаю создать enum с темы значениями для трёх видов кнопок

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/CalculatorButtons.swift
> +				UIView.animate(withDuration: 0.2) { [weak self] in
Для анимации weak self не нужен

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/CalculatorButtons.swift
> +		if self.tag == 0 {
Вот тут tag использовать нормально

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	}
Это можно удалить

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	}
У тебя есть похожая функция в ConverterRPN, но в одном случае возвращается 1, а в другом -1. Так и должно быть?

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/ConverterRPN/ConverterRPN.swift
> +	func evaluateRpn(elements: [String]) -> Double {
Публичные функции лучше располагать выше приватных

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/Views/ButtonsStackView.swift
> +		setupButton()
Пишешь button, а это stack

2019-11-25 15:34 UTC, ArtemPrivet commented on Calculator/Calculator/Views/CalcalatorView.swift
> +		for index in 0...18 {
Почему 18? У тебя же есть buttons.count

2019-11-25 20:07 UTC, ikirillfedorov commented on Calculator/Calculator/CalculatorButtons.swift
> +	private func setButtonsColor() {
Если не изменяет память потому - что тут у кнопок был таг, потом понял, что это ошибка и перенес в инит.  В последнем коммите уже отражены эти измеения. 
fxd

2019-11-25 20:09 UTC, ikirillfedorov commented on Calculator/Calculator/CalculatorButtons.swift
> +				UIView.animate(withDuration: 0.2) { [weak self] in
понял, fxd

2019-11-25 20:10 UTC, ikirillfedorov commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	}
что то тут делал потом перенес, а уже ненужный метод забыл убрать. 
fxd

2019-11-25 20:11 UTC, ikirillfedorov commented on Calculator/Calculator/ConverterRPN/ConverterRPN.swift
> +	func evaluateRpn(elements: [String]) -> Double {
fxd

2019-11-25 20:12 UTC, ikirillfedorov commented on Calculator/Calculator/Views/ButtonsStackView.swift
> +		setupButton()
копировал из файла с кнопками и забыл переименовать. 
fxd

2019-11-25 20:13 UTC, ikirillfedorov commented on Calculator/Calculator/Views/CalcalatorView.swift
> +		for index in 0...18 {
справедливо
fxd

2019-11-25 20:14 UTC, ikirillfedorov commented on Calculator/Calculator/CalculatorButtons.swift
> +		if self.tag == 0 {
ок

2019-11-25 20:27 UTC, ikirillfedorov commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	}
Да, в ConverterRPN приходят значения операнд им задаю наименьший приоритет, им ставлю наименьший приоритет в виде -1 далее. 
А в контроллере может прийти всего 2 кейса, так как обрабатываются только операторы, defoult стоит "затычка"

2019-11-25 20:28 UTC, ikirillfedorov commented on Calculator/Calculator/CalculatorButtons.swift
> +		if self.tag == 0 {
ок

2019-11-25 21:20 UTC, ikirillfedorov commented on Calculator/Calculator/CalculatorButtons.swift
> +			switch self.tag {
fxd

2019-12-03 12:12 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:12 UTC, closed without merging