medvedev_mikhail/calculator
ArtemPrivet/FocusStartHomeworks pull request #79
Opened 2019-11-22 21:59 UTC by c0dedbear

Не успел доработать анимацию кнопки деления так как у нее фон - картинка.
Сорян, тесты не успел написать, завтра занятие надо спать идти, а то котелок не варит уже...

2019-11-26 19:30 UTC, MisnikovRoman requested changes
- Что-то не то с отступами между кнопками - вертикальные и горизонтальные отступы разные
-  Почему-то тормозит при вводе данных (если быстро нажать на цифру 1 шесть раз на экране будет "11") - скорее всего из-за анимаций в файле `Buttons.swift`
- 1 + 2 / 3 = 5,8333 - вот такого точно не ожидал. В общем где-то что-то не очищается если просто вводить операции одна за одной: 1,+,2,/,3,=,1,+,2,/,3,= то тут результат будет 2,333
- Можно делить на ноль + после этого не работает кнопка сброса

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				E935E37C2382F53000E417EA /* Recovered References */,
вот тут скорее всего что-то не так, потому что Xcode создал папку с восстановленными файлами

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				LastSwiftUpdateCheck = 1120;
А что это за свойство?

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator.xcodeproj/project.pbxproj
> -				DEVELOPMENT_TEAM = 8TTR7A9Y64;
Старайся такое не коммитить (минор)

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	// MARK: - PROPERTIES
Минор, но с капсом нужно осторожнее

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/MyFormatter.swift
> +	static let shared = MyFormatter()
а зачем тут синглтон?

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/MyFormatter.swift
> +final class MyFormatter
Ну и название, конечно не годится

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			}
Свитч тут бесполезен

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				// это число
а как же сепаратор?

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func addTargetToButtons() {
Все приватные методы можно вынести в отдельный приватный экстеншн
``` swift
private extension CalculatorViewController
{
  func addTargetToButtons() {
  // ...
}
```

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			if let double = Double(filter) {
можно легко упростить и уменьшить вложенность записав через запятую 2 условия

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			calculatorView.screenLabel.text = isDigitNotSeparator ?  digit : Sign.zero + digit
лишний пробел после `?`

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func toggleButtonState(of sender: Button) {
если я правильно понимаю, то непосредственного тогла тут не происходит(смена значения на противоположное), а просто вычисляется новое состояние исходя из внутренних условий. Если так, то нужно переименовать метод

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func toggleClearButtonTitle() {
тут тоже нет тогла

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func updateDisplay() {
Тут бы больше подошло название `updateResultLabel`. а то кажется как будто ты весь экран перерисовываешь

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	@objc private func swipeOnLabel() {
позволяет стирать результат по одной цифре, такого быть не должно

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/Calculator.swift
> +		// тело выражения
комменты, которые дублирую название типа можно не писать и так все понятно

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/Calculator.swift
> +		let funcSign: String 					// знак операции
не нужно бояться использовать полные названия для переменных `functionSign`

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/Calculator.swift
> +	mutating func evaluate() -> ( result: Double?, isWaiting: Bool) {
странно, что основной метод класса находится в экстеншене. Лучше бы он был наверху, а приватные метод в экстеншене

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/RPNEncoder.swift
> +	var expressionsAsRPN = [String]() //  массив выражений сконвертированный в RPN
мне кажется, логичнее выполнять обработку выражения не в ините, а отдельным методом
``` swift
class RPNEncoder 
{
  func toRPN(expression: [String]) ->  [String] {
    // ...
  }
}
```
Таким образом если нам потребуется, например, выполнений несколько параллельных операций у нас не возникнет проблем

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Models/RPNDecoder.swift
> +	private static func evaluatedRPN(expressionInArrayFormat: [String]) -> Double {
Исходя из названий у тебя получается, что энкодер и декодер должны заниматься одинаковыми вещами, но прямом и обратном направлении.
А по факту энкодер конвертирует `[String] -> [String]`, а декодер `[String] -> [Double]`

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/ButtonsStack.swift
> +		if UIScreen.main.bounds.width <= 320 {
числовые константы лучше вынести в отдельный енам с константами
``` swift 
enum Metrics 
{
  static let maxSmallScreenWidth = 320
  static let rowPadding = 16
  // ...
}
```

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +	private func createSubviews() {
🤔 но ты же не тут создаешь сабвьюхи?

2019-11-26 19:30 UTC, MisnikovRoman commented on Calculator/Calculator/Views/CalculatorView.swift
> +			UILayoutPriority(1),
а это зачем?

2019-11-26 20:02 UTC, c0dedbear commented on Calculator/Calculator/Models/MyFormatter.swift
> +	static let shared = MyFormatter()
Где то прочитал, что создание экземляра NumberFormatter требовательно к ресурсам. Поэтому решил сделать синглтон.

2019-11-26 20:04 UTC, c0dedbear commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				E935E37C2382F53000E417EA /* Recovered References */,
Что с этим делать?

2019-11-26 20:06 UTC, c0dedbear commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				LastSwiftUpdateCheck = 1120;
Без понятия, гугл говорит что что связанное с настройками xcode.

2019-11-27 15:21 UTC, c0dedbear commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				E935E37C2382F53000E417EA /* Recovered References */,
> * Что-то не то с отступами между кнопками - вертикальные и горизонтальные отступы разные
> * Почему-то тормозит при вводе данных (если быстро нажать на цифру 1 шесть раз на экране будет "11") - скорее всего из-за анимаций в файле `Buttons.swift`
> * 1 + 2 / 3 = 5,8333 - вот такого точно не ожидал. В общем где-то что-то не очищается если просто вводить операции одна за одной: 1,+,2,/,3,=,1,+,2,/,3,= то тут результат будет 2,333
> * Можно делить на ноль + после этого не работает кнопка сброса

**Исправлено.**

![Screen Recording 2019-11-27 at 18 04 31](https://user-images.githubusercontent.com/21219011/69735942-9a274500-1142-11ea-8d41-60f3ae5deb8a.gif)

P.S. Гифка что то тормозная, видать пережимает.

2019-11-27 15:22 UTC, c0dedbear commented on Calculator/Calculator.xcodeproj/project.pbxproj
> -				DEVELOPMENT_TEAM = 8TTR7A9Y64;
Ок

2019-11-27 15:22 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	// MARK: - PROPERTIES
Поправил)

2019-11-27 15:23 UTC, c0dedbear commented on Calculator/Calculator/Models/MyFormatter.swift
> +final class MyFormatter
Переименовал в DisplayFormatter

2019-11-27 15:26 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			}
Убрал

2019-11-27 18:04 UTC, MisnikovRoman commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				E935E37C2382F53000E417EA /* Recovered References */,
> Что с этим делать?

Смотреть что там за файлы в папке и либо удалить их, либо перенести в нужную папку

2019-11-27 18:07 UTC, MisnikovRoman commented on Calculator/Calculator/Models/MyFormatter.swift
> +	static let shared = MyFormatter()
Никто не мешает создавать объект в AppDelegate, а затем передавать ссылку в нужные модуль через DI

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				// это число
Учел

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func addTargetToButtons() {
Сделано

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			if let double = Double(filter) {
Учел

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			calculatorView.screenLabel.text = isDigitNotSeparator ?  digit : Sign.zero + digit
Глаз алмаз =) Поправил.

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func toggleButtonState(of sender: Button) {
Да верно, поправил.

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func toggleClearButtonTitle() {
Переименовал.

2019-11-27 20:34 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	private func updateDisplay() {
Переименовал

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	@objc private func swipeOnLabel() {
Исправил

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Models/Calculator.swift
> +		// тело выражения
Учел

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Models/Calculator.swift
> +		let funcSign: String 					// знак операции
Учел

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Models/Calculator.swift
> +	mutating func evaluate() -> ( result: Double?, isWaiting: Bool) {
Перенес в extension приватные структуры и перечисления, а также приватные методы. Разгрузил  метод evaluate() от вложенности.

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Models/RPNEncoder.swift
> +	var expressionsAsRPN = [String]() //  массив выражений сконвертированный в RPN
Объединил логику RPN Encoder/ Decoder в одну структуру - RPNConverter, сделал отдельные методы без использования инита.

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Models/RPNDecoder.swift
> +	private static func evaluatedRPN(expressionInArrayFormat: [String]) -> Double {
Объединил логику RPN Encoder/ Decoder в RPNConverter.

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Views/ButtonsStack.swift
> +		if UIScreen.main.bounds.width <= 320 {
Они оказались не нужными.

2019-11-27 20:35 UTC, c0dedbear commented on Calculator/Calculator/Views/CalculatorView.swift
> +			UILayoutPriority(1),
![image](https://user-images.githubusercontent.com/21219011/69757440-108d6c80-116e-11ea-9e49-ab33caece674.png)

2019-11-27 20:37 UTC, c0dedbear commented on Calculator/Calculator/Views/CalculatorView.swift
> +	private func createSubviews() {
Да, только добавляю, исправил.

2019-11-27 20:38 UTC, c0dedbear commented on Calculator/Calculator/Views/CalculatorView.swift
> +			UILayoutPriority(1),
Убрал

2019-11-27 20:50 UTC, c0dedbear commented on Calculator/Calculator/Models/MyFormatter.swift
> +	static let shared = MyFormatter()
А чем плох синглтон в конкретном данном случае и под эту задачу?
DI это Dependency Injection? Через инициализатор?

2019-11-27 20:50 UTC, c0dedbear commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				E935E37C2382F53000E417EA /* Recovered References */,
> > Что с этим делать?
> 
> Смотреть что там за файлы в папке и либо удалить их, либо перенести в нужную папку

Удалил. Там каких то два файла было с Pod_

2019-12-03 12:10 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:10 UTC, closed without merging