rutsman_aleksandr/calculator
ArtemPrivet/FocusStartHomeworks pull request #80
Opened 2019-11-23 15:44 UTC by svshkv

2019-11-27 18:55 UTC, MisnikovRoman requested changes
- Отcутствуют файлы в проекте (CalculatorView и ButtonsService), соответственно проект не собирается
- Не использован шрифт из проекта
- 1+2/3 = 0.333
- 200+50% = 1.0
- результат всегда отображается с запятой
- выражения с минусом плохо работают (если изменить знак у результата вычисления)

2019-11-27 18:55 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.view = CalculatorView(frame: self.view.frame)
для этого специально есть метод `loadView`

2019-11-27 18:55 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let view = view as? CalculatorView else { return }
а зачем тут использовать кастинг типов если можно инициализацию CalculatorView вынести в отдельную переменную?

2019-11-27 18:55 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let view = view as? CalculatorView else { return }
у тебя же есть переменная self.calculatorView

2019-11-27 18:55 UTC, MisnikovRoman commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			view.calculatingLabel.text = ""
одинаковую строку можно вынести из всех условий

2019-11-27 18:55 UTC, MisnikovRoman commented on Calculator/Calculator/Services/ButtonsService.swift
> +	func numbersTapped(_ view: CalculatorView, _ sender: UIButton) {
Сервисы не должны ничего знать о UI компонентах

2019-12-01 14:43 UTC, svshkv commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		self.view = CalculatorView(frame: self.view.frame)
libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform. - выдает такую ошибку. (Я гуглил решение. Пришел к выводу, что лучше оставить во viewDidLoad 😅)

2019-12-01 14:43 UTC, svshkv commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let view = view as? CalculatorView else { return }
Исправил

2019-12-01 14:44 UTC, svshkv commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +		guard let view = view as? CalculatorView else { return }
Исправил

2019-12-01 14:46 UTC, svshkv commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +			view.calculatingLabel.text = ""
Не могу вынести ее, так как эта функция вызывается и при нажатии на цифры. То есть тогда лейбл будет обнуляться при нажатии на цифры.

2019-12-03 12:10 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:10 UTC, closed without merging