belousova_anna/calculator
ArtemPrivet/FocusStartHomeworks pull request #81
Opened 2019-11-24 00:15 UTC by anna-belousova

![1446405535_92965515](https://user-images.githubusercontent.com/52084327/69487308-a7a1ae00-0e68-11ea-8ea2-7798c0df158f.jpg)

2019-11-25 17:23 UTC, ArtemPrivet requested changes

2019-11-25 17:23 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	@objc private func setTarget(_ sender: UIButton) {
И все же это не setTarget, а как минимум buttonTapped

2019-11-25 17:23 UTC, ArtemPrivet commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				screen.button.buttonArray[15].titleLabel?.text = " C"
Мы через несколько классов знаем что в каком то массиве надо дернуть 15 элемент. Давай лучше отдельную функцию заведём, которая будет настраивать title для кнопки. 
И почему тут пробел перед  С?

2019-11-25 17:23 UTC, ArtemPrivet commented on Calculator/Calculator/Service/Calculation.swift
> +		guard labelText.count <= 8 else { return labelText }
Давай вынесем 8 в константу, чтобы было понятно что эта цифра значит

2019-11-25 17:23 UTC, ArtemPrivet commented on Calculator/Calculator/Service/Calculation.swift
> +		return labelText
Давай не три раза вызывать label, а сначала мы посчитаем что в нем должно отобразиться, а потом уже засунем результат в labelText

2019-11-25 17:23 UTC, ArtemPrivet commented on Calculator/Calculator/View/Button.swift
> +	private let count = 19
А зачем нам тут count, когда у массива есть свойство count?

2019-11-25 17:23 UTC, ArtemPrivet commented on Calculator/Calculator/View/Button.swift
> +			case 0, 1, 3, 4, 5, 7, 8, 9, 11, 12, 13:
Можно создать subclass от UIButton, и сделать у него свойство type. В котором был бы enum из трёх вариантов. При создании кнопки ты бы задавала в зависимости от названия кнопки её тип, и тогда не пришлось бы тут через индексы работать

2019-11-25 21:29 UTC, anna-belousova commented on Calculator/Calculator/View/Button.swift
> +	private let count = 19
Я использую count = 19 для создания массива кнопок, когда buttonArray еще пустой и buttonArray.count равен 0

2019-11-25 22:50 UTC, anna-belousova commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +	@objc private func setTarget(_ sender: UIButton) {
fixed

2019-11-25 22:51 UTC, anna-belousova commented on Calculator/Calculator/Service/Calculation.swift
> +		guard labelText.count <= 8 else { return labelText }
fixed

2019-11-26 08:43 UTC, anna-belousova commented on Calculator/Calculator/Controllers/CalculatorViewController.swift
> +				screen.button.buttonArray[15].titleLabel?.text = " C"
Добавила функцию в класс Button. Добавляла пробел для костыльного выравнивания и забыла исправить.

2019-11-26 08:43 UTC, anna-belousova commented on Calculator/Calculator/Service/Calculation.swift
> +		return labelText
fixed

2019-11-26 09:02 UTC, anna-belousova commented on Calculator/Calculator/View/Button.swift
> +			case 0, 1, 3, 4, 5, 7, 8, 9, 11, 12, 13:
Если я инициализирую кнопку с типом при создании, я не могу потом передать ее в Screen без типа. Не знаю, как это сделать, чтобы не сломать структуру классов Button и Screen.
Еще добавила выравнивание title по левому краю для кнопки 0.

2019-11-30 14:00 UTC, ArtemPrivet commented on Calculator/Calculator/View/Button.swift
> +	private let count = 19
ButtonArray пустой, да. Но ты же создаешь кнопки исходя из symbolArray, а он то уже полный и там ровно и symbolArray.count = 19 как раз

2019-12-01 18:55 UTC, anna-belousova commented on Calculator/Calculator/View/Button.swift
> +	private let count = 19
Исправила

2019-12-03 12:12 UTC, ArtemPrivet commented
Принято ✅

2019-12-03 12:12 UTC, closed without merging