fedorov_kirill/marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #85
Opened 2019-12-06 05:24 UTC by ikirillfedorov

К сожалению, не успел доделать полностью.

2019-12-06 13:22 UTC, ArtemPrivet requested changes

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		tabBarController.addChild(UINavigationController(rootViewController: authorVC))
Лучше вынести создание TabBarController'a в отдельный класс(наследник UITabBarController), и в нем уже все это настроить. А то такая настройка выглядит громоздко и выходит за рамки ответственности AppDelegate

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +import UIKit
А зачем нам тут UIKit?

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private func fetchData(from url: URL, _ completion: @escaping(DataResult) -> Void) {
Приватные функции лучше внизу располагать

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +				guard let image = UIImage(data: data) else { return }
Но если ты упадешь в else, то completion у тебя не вызовется

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		if let seatchText = searchResult {
seatch 🤷‍♂️

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		guard let url = getCharactersRequest(comicsId: objectId, searchResult: searchResult) else { return }
completion в else

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		fetchData(from: url) { dataResult in
weak self

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +				print(error.localizedDescription)
Принт уже не нужен

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +typealias DataResult = Result<Data, ServiceError>
Лучше разделить на отдельные репозитории, а не грузить все в одном.
Плюс закрыть репозиторий протоколом

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private func getComicsRequest(fromPastScreen: String?, characterId: String?, searchResult: String?) -> URL? {
А почему у тебя все опционально тут? ДА и делать проверку на стринги не очень продуктивно(я про fromPastScreen)

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private func getComicsRequest(fromPastScreen: String?, characterId: String?, searchResult: String?) -> URL? {
Возможно стоит разделить на несколько методов или еще лучше, сделать отдельный класс Builder, который бы собирал URL исходя из компонентов, которые в него добавили. Но это так, если будет время

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		fetchData(from: url) { comicsResult in
weak self

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		}
let objectId = id.map(String.init) или так let test = id.map { String($0) }

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +			urlString = "\(Urls.baseUrl)\(Urls.authorEndpoint)/\(comicsId)/\(Urls.comicsEndpoint)" //FIXIT
Пофиксил?

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		fetchData(from: url) { authorResult in
weak self

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		guard let url = getAuthorRequest(comicsId: objectId, searchResult: searchResult) else { return }
completion после else

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +
Лишний отступ

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +import UIKit
Презентер не должен знать про UIKit

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +						self.authorView?.activityIndicator.stopAnimating()
Должно быть self.authorView?.stopAnimating() без доступа к индикатору

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +						self.authorView?.activityIndicator.stopAnimating()
А вот в случае ошибки можно и какой-то alert показать

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +						cell.imageView?.layer.cornerRadius = imageView.bounds.width / 2
И опять же, у тебя логика View просачилась в презентер. Роль презентера лишь подготовить информацию, а уже как ее отображать(настройка ячейки) это роль View

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsRouter.swift
> +	var factory: Factory
private

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +	let loadAuthorsQueue = DispatchQueue(label: "loadAuthorsQueue", qos: .userInteractive, attributes: .concurrent)
Почему repository и router var? и почему все эти свойства internal?

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private var dataTask: URLSessionDataTask?
Нигде не используется

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +	let refreshControl = UIRefreshControl()
Тоже private

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +	var activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
let

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +		self.activityIndicator.startAnimating()
Он точно должен начать крутиться при init'e?

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +extension AuthorsViewController: UITableViewDataSource, UITableViewDelegate
Лучше разделить на 2 extension

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersRouter.swift
> +	var factory: Factory
private let

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersViewController.swift
> +	var activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
private let

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersViewController.swift
> +}
Контроллер очень похож на AuthorsViewController. Не думал сделать базовый класс и от него отнаследоваться вместе того, чтобы копировать код?

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharctersPresenter.swift
> +	let loadCharactersQueue = DispatchQueue(label: "loadCharactersQueue", qos: .userInteractive, attributes: .concurrent)
То же самое что и в другом презентере private let

2019-12-06 13:22 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/DetailsComicsModule/DetailsComicaRouter.swift
> +import Foundation
Хм

2019-12-07 08:55 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		tabBarController.addChild(UINavigationController(rootViewController: authorVC))
fxd

2019-12-07 08:57 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +import UIKit
typealias ImageResult = Result<UIImage, ServiceError>
Используется UIImage

2019-12-07 09:01 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private func fetchData(from url: URL, _ completion: @escaping(DataResult) -> Void) {
fixed

2019-12-07 09:08 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +				guard let image = UIImage(data: data) else { return }
fxd

2019-12-07 09:10 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		if let seatchText = searchResult {
fxd

2019-12-07 09:11 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		guard let url = getCharactersRequest(comicsId: objectId, searchResult: searchResult) else { return }
fxd

2019-12-07 09:12 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		fetchData(from: url) { dataResult in
fxd

2019-12-07 09:18 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +				print(error.localizedDescription)
fxd

2019-12-07 09:23 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		fetchData(from: url) { comicsResult in
fxd

2019-12-07 09:26 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +			urlString = "\(Urls.baseUrl)\(Urls.authorEndpoint)/\(comicsId)/\(Urls.comicsEndpoint)" //FIXIT
ага))
убрал

2019-12-07 09:31 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		guard let url = getAuthorRequest(comicsId: objectId, searchResult: searchResult) else { return }
fxd

2019-12-07 09:32 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +
fxd

2019-12-07 09:36 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +import UIKit
fxd по всему проекту

2019-12-07 09:40 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsRouter.swift
> +	var factory: Factory
fxd

2019-12-07 11:43 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		fetchData(from: url) { authorResult in
fxd

2019-12-08 15:18 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +typealias DataResult = Result<Data, ServiceError>
Разделил на отдельные репозитории и все закрыл протоколами

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private func getComicsRequest(fromPastScreen: String?, characterId: String?, searchResult: String?) -> URL? {
fromPastScreen заменил на enum
Опционалы т.к. могут быть nil если загрузка идет без поиска и без id 
Сбор url вынес в отдельный класс UrlBuilder

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +		}
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +						self.authorView?.activityIndicator.stopAnimating()
fxd, вынес в протокол

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +						self.authorView?.activityIndicator.stopAnimating()
Добавил демонстрацию алерта

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +						cell.imageView?.layer.cornerRadius = imageView.bounds.width / 2
вынес все в протоколы, презентер больше не общается с элементами вью, а только "говорит", что сделать

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsPresenter.swift
> +	let loadAuthorsQueue = DispatchQueue(label: "loadAuthorsQueue", qos: .userInteractive, attributes: .concurrent)
сделал let / установил модификторы доступа

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/Repository.swift
> +	private var dataTask: URLSessionDataTask?
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +	let refreshControl = UIRefreshControl()
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +	var activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +		self.activityIndicator.startAnimating()
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +extension AuthorsViewController: UITableViewDataSource, UITableViewDelegate
Разделил

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersRouter.swift
> +	var factory: Factory
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersViewController.swift
> +	var activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
fxd

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersViewController.swift
> +}
Сделал родительский класс для основного контроллера и для дитейлс контроллера, дальше наследовался от них.

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharctersPresenter.swift
> +	let loadCharactersQueue = DispatchQueue(label: "loadCharactersQueue", qos: .userInteractive, attributes: .concurrent)
поправил, сделал везде private

2019-12-08 15:19 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/DetailsComicsModule/DetailsComicaRouter.swift
> +import Foundation
была заготовка на продолжение...

2019-12-08 15:58 UTC, ArtemPrivet requested changes

2019-12-08 15:58 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		let tabBarController = MarvelTabBarController(nibName: nil, bundle: nil)
Чтобы прям вообще красота была, можно создать свой инит, чтобы можно было написать просто MarvelTabBarController() без nibName и bundle

2019-12-08 15:58 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/BusinessLayer/AuthorsRepository.swift
> +	let dataRepository: IDataRepository
Это похоже на какое то читерство. Видел где ты это вызываешь и выглядит это не очень хорошо. ЧТО ты из одного репозитория другой репозиторий дергаешь. В принципе так можно оставить, но если получится избавиться от такой зависимости, то будет классно

2019-12-08 15:58 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +	let presenter: IAuthorsPresenter
Он должен быть доступен извне?

2019-12-08 15:58 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersViewController.swift
> +		tableView.delegate = self
Лишний делегат

2019-12-08 15:58 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Modules/ComicsModule/ComicsViewController.swift
> +		tableView.delegate = self
Тоже лишний делегат

2019-12-08 16:54 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		let tabBarController = MarvelTabBarController(nibName: nil, bundle: nil)
fxd

2019-12-08 16:54 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/BusinessLayer/AuthorsRepository.swift
> +	let dataRepository: IDataRepository
Не знаю насколько это валидно, но я сделал DataRepository родительским классом и унаследовался от него. Теперь не требует внедрения зависимости.

2019-12-08 16:54 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/AuthorsModule/AuthorsViewController.swift
> +	let presenter: IAuthorsPresenter
Нет, установил модификтор доступа private

2019-12-08 16:54 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/CharactersModule/CharactersViewController.swift
> +		tableView.delegate = self
fxd

2019-12-08 16:54 UTC, ikirillfedorov commented on MarvelHeroes/MarvelHeroes/Modules/ComicsModule/ComicsViewController.swift
> +		tableView.delegate = self
fxd

2019-12-10 08:33 UTC, closed without merging