shalashnikov_maxim/marvel_heroes
ArtemPrivet/FocusStartHomeworks pull request #86
Opened 2019-12-06 13:13 UTC by b0sya

Пока что отправляю минимальную версию. Не хочу начинать следующую часть задания, потому что, по моему мнению, там достаточно много копипаста, а сейчас есть проблемы с архитектурой (repository в моей реализации не имеет смысла как мне кажется).

2019-12-06 18:13 UTC, ArtemPrivet requested changes

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoTableViewCell.swift
> +	var comicLabel = UILabel()
Лучше сделать их приватными и написать функцию, которая бы устанавливала им значения
`func set(comicCover: UIImage, text: String) {...}`

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	let gradient = CAGradientLayer()
Все эти свойства должны быть private

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	private let cdllId = "cell"
Это лучше перенести в саму ячейку
И еще тут ошибка в написании

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	var presenter: ICharacterInfoPresenter?
Смотри, у тебя в презентере уже есть опциональная view, так что лучше ее сделать `internal`, а этот презентер сделать `private` и убрать опциональность

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +	func getImage()
функция get.. должна что-то возвращать

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +					self.view?.characterImage.image = result
Не должно быть в презентере возможности менять напрямую UI компоненты

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +		}
А почему ты тут переключаешься на main?

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +		repository.loadComics(by: id) { result in
weak self

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +	}
Такое, кстати, можно делать через computed property

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +		repository.loadCharacterImage(for: comicsImage, size: ImageSize.small) { comic in
weak self

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Characters/CharactersPresenter.swift
> +				}
Можно же одним DispatchQueue.main.async обойтись

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Characters/CharactersPresenter.swift
> +		repository.loadCharacters { characters in
weak self

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Characters/CharactersPresenter.swift
> +			}
Тут тоже не надо на каждое действие вызывать `DispatchQueue.main.async`, а можно все в один завернуть

2019-12-06 18:13 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Repository.swift
> +
Собственно да, у тебя репозитой получился бесполезным. Вся логика у тебя в сервисе. Давай сделаем так, чтобы repository занимался декодингом данных, полученных из сервиса. А то у нас у сервиса слишком много ответственности

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoTableViewCell.swift
> +	var comicLabel = UILabel()
fixed

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	let gradient = CAGradientLayer()
fixed

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	private let cdllId = "cell"
fixed

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	var presenter: ICharacterInfoPresenter?
fixed

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +		repository.loadCharacterImage(for: comicsImage, size: ImageSize.small) { comic in
fixed

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Characters/CharactersPresenter.swift
> +				}
fixed

2019-12-07 10:35 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Characters/CharactersPresenter.swift
> +		repository.loadCharacters { characters in
fixed

2019-12-07 10:36 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Repository.swift
> +
fixed

2019-12-07 10:36 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Characters/CharactersPresenter.swift
> +			}
fixed

2019-12-10 13:44 UTC, ArtemPrivet requested changes

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Builder.swift
> +final class Builder: IBuilder
`Builder` слишком абстракное название. Надо назвать так, чтобы было понятно, что мы создаем.

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	private let presenter: ICharacterInfoPresenter
Минор. Лучше группировать свойства вмете. То бишь сначала все значения с `let`, а потом уже с `var`

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +	internal var view: CharacterInfoViewController?
internal можно не писать

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +				print(message)
Лучше не принтовать, а показывать алерты с ошибкой

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesModel.swift
> +final class HeroesModel: IHeroesModel
А для чего нужен этот класс?

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/RemoteDataService.swift
> +	func loadComics(by characterID: Int, _ completion: @escaping (DataResult) -> Void)
Минор. Можно не писать нижнее подчеркивание перед completion

2019-12-10 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Repository.swift
> +	func decodeCharacters(_ completion: @escaping (CharacterResult) -> Void){
У тебя функция decode загружает что-то. Тут либо ошибка в нейминге либо в логике

2019-12-11 11:18 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Repository.swift
> +	func decodeCharacters(_ completion: @escaping (CharacterResult) -> Void){
fixed

2019-12-11 11:18 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/RemoteDataService.swift
> +	func loadComics(by characterID: Int, _ completion: @escaping (DataResult) -> Void)
fixed

2019-12-11 11:18 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/HeroesModel.swift
> +final class HeroesModel: IHeroesModel
Забыл удалить, fixed

2019-12-11 11:18 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +	internal var view: CharacterInfoViewController?
fixed

2019-12-11 11:18 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Builder.swift
> +final class Builder: IBuilder
fixed

2019-12-11 11:22 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/RemoteDataService.swift
> +	func loadComics(by characterID: Int, _ completion: @escaping (DataResult) -> Void)
fixed

2019-12-11 11:22 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewController.swift
> +	private let presenter: ICharacterInfoPresenter
fixed

2019-12-11 12:33 UTC, ArtemPrivet requested changes

2019-12-11 12:33 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AppDelegate.swift
> +	let builder = ControllerBuilder()
builder надо бы сделать private

2019-12-11 12:33 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/CharacterInfo/CharacterInfoViewPresenter.swift
> +	internal var view: CharacterInfoViewController?
internal так и не убрал

2019-12-11 12:33 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Characters/CharactersViewController.swift
> +	let tableView = UITableView()
А почему таблица торчит наружу?

2019-12-12 13:44 UTC, ArtemPrivet requested changes

2019-12-12 13:44 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Repository.swift
> +typealias ComicResult = Result<[Comic]?, ServiceError>
По идее в Result не должен в случае success приходить опционал. Давай от него избавимся

2019-12-13 18:10 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Repository.swift
> +typealias ComicResult = Result<[Comic]?, ServiceError>
fixed

2019-12-13 18:10 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/Characters/CharactersViewController.swift
> +	let tableView = UITableView()
fixed

2019-12-13 18:10 UTC, b0sya commented on MarvelHeroes/MarvelHeroes/AppDelegate.swift
> +	let builder = ControllerBuilder()
fixed

2019-12-15 13:13 UTC, ArtemPrivet commented
Принято

2019-12-15 13:13 UTC, closed without merging