medvedev_ivan/marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #87
Opened 2019-12-06 13:30 UTC by Med1D

Если смотреть на даты создания файлов, то можно увидеть как проходит жизнь.🤯
Иногда наблюдаю "приколы" с картинками, они почему-то иногда в странном порядке загружаются. Мб проблема многопоточности. Надеюсь если проблема не в API, то разберем это.

2019-12-06 13:33 UTC, Med1D commented
Кто юзнет мои keys не в благих целях, тот плохой человек.
100% PROTECTED

2019-12-06 13:35 UTC, Med1D commented
`⚠️ Важно Название проекта должно быть MarvelHeroes.xcodeproj и файлы проекта должны находится в папке MarvelHeroes`
Не собирается, потому что нет workspace, что не соответствует ТЗ.

2019-12-06 18:42 UTC, ArtemPrivet requested changes
Потом допроверю еще

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsPresenter.swift
> +	let dispatchQueue = DispatchQueue(label: "loadImages", qos: .userInteractive)
ЧТо-то из этого точно долдно быть private и вместо var должно быть let

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsPresenter.swift
> +				self.authorDetailsView?.showData(withImageData: self.authorImageData, withComicsCount: self.comicsImagesData.count)
Принты удаляем

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsPresenter.swift
> +		self.author.comics?.items?.forEach { [weak self] comic in
вот тут weak self не нужен

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsPresenter.swift
> +			self.repository.getComic(withUrlString: comic.resourceURI, { comicResult in
а тут нужен

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsPresenter.swift
> +				self.repository.getImage(urlString: imageUrlString, { [weak self] dataOptionalResult in
URL уже лучше в репозитории настраивать

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsView.swift
> +	let labelComicsNotFound = UILabel()
Это все должно быть private

2019-12-06 18:42 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/AuthorDetails/AuthorDetailsView.swift
> +	let cellReuseIdentifier = "cell"
А identifier можно засунуть в ячейку как static переменную

2019-12-10 15:39 UTC, MisnikovRoman reviewed
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002c19090 UIScrollView:0x7f805485c800.bottom == UIKBTutorialMultipageView:0x7f8053247c80.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2019-12-10 18:37:27.527815+0300 MarvelHeroes[22530:653931] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002c9b610 V:|-(0)-[UIKBTutorialMultipageView:0x7f8053247c80]   (active, names: '|':UIView:0x7f8053242cd0 )>",
    "<NSLayoutConstraint:0x600002cca8f0 V:[UIKBTutorialMultipageView:0x7f8053247c80]-(>=0)-[UIButton:0x7f80532498e0'Continue']   (active)>",
    "<NSLayoutConstraint:0x600002c73de0 V:|-(0)-[UIView:0x7f8053242cd0]   (active, names: UIContinuousPathIntroduct...:0x7f8050f23010, '|':UIContinuousPathIntroduct...:0x7f8050f23010 )>",
    "<NSLayoutConstraint:0x600002c05770 UIContinuousPathIntroduct....top == TUISystemInputAssistantView:0x7f8053206c90.top   (active, names: UIContinuousPathIntroduct...:0x7f8050f23010 )>",
    "<NSLayoutConstraint:0x600002c05e00 UIContinuousPathIntroduct....bottom == UIInputSetContainerView:0x7f8053166b20.bottom   (active, names: UIContinuousPathIntroduct...:0x7f8050f23010 )>",
    "<NSLayoutConstraint:0x600002c65950 UILayoutGuide:0x6000036a3640'UIViewSafeAreaLayoutGuide'.bottom == UIView:0x7f8053242cd0.bottom   (active)>",
    "<NSLayoutConstraint:0x600002c9b700 UIButton:0x7f80532498e0'Continue'.height == 21   (active)>",
    "<NSLayoutConstraint:0x600002c9b6b0 V:[UIButton:0x7f80532498e0'Continue']-(0)-|   (active, names: '|':UIView:0x7f8053242cd0 )>",
    "<NSLayoutConstraint:0x600002c7b340 'assistantView.top' V:|-(0)-[TUISystemInputAssistantView:0x7f8053206c90]   (active, names: '|':UIInputSetHostView:0x7f805316e6d0 )>",
    "<NSLayoutConstraint:0x600002cf4c30 'UIInputViewSetPlacement_GenericApplicator<UIInputViewSetPlacementOffScreenDown>.vertical' V:[UIInputSetContainerView:0x7f8053166b20]-(0)-[UIInputSetHostView:0x7f805316e6d0]   (active)>",
    "<NSLayoutConstraint:0x600002c7bed0 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x6000036a3640'UIViewSafeAreaLayoutGuide']-(34)-|   (active, names: UIContinuousPathIntroduct...:0x7f8050f23010, '|':UIContinuousPathIntroduct...:0x7f8050f23010 )>"
)

2019-12-10 16:31 UTC, MisnikovRoman requested changes
- Очень много дублирования кода в файлах модулей, напрашивается использование наследования
- Если протоколов много, то их лучше держать вместе с классами, а не в отдельной папке

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		window.backgroundColor = #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1)
настройка цвета в AppDelegate 😮 цвет фона нужно менять в VC

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +	}()
для этого есть фабрика

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		authorsNavigationController.pushViewController(authorsVC, animated: false)
лучше создавать навигейшн контроллер в фабрике через инициализатор с rootVC

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Factory/Factory.swift
> +		let repository = Repository()
репозиторий лучше создавать вне фабрики и пробрасывать через инициализатор. и тем более не стоит при создании каждого модуля создавать отдельный экземпляр репозитория

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Factory/Factory.swift
> +		let heroeDetailsView = HeroeDetailsView(heroeDetailsPresenter: heroeDetailsPresenter)
hero

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Repository/Repository.swift
> +
лишний энтер

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Repository/Repository.swift
> +	let networkService = NetworkService()
опять же нужно не создавать сервис, а нужно прикидывать его зависимость

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Repository/Repository.swift
> +	func getHeroes(withHeroeName name: String?, _ completion: @escaping (HeroesResult) -> Void) {
по хорошему нужно разбивать на несколько репозиториев:
- HeroesRepository
- ComicsRepository
- AuthorsRepository

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +	func getComic(withUrlString urlString: String?, _ completion: @escaping (ComicsResult) -> Void) {
практически полностью дублирует `func getComics(withComicName:, _:)`

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +extension NetworkService
достаточно 1 раз написать `private extension`, чтобы у каждого метода не писать `private func`

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +	private func createURL(withHeroeName heroeName: String?) -> URL? {
Ну и в целом тут напрашивается отдельная сущность URLBuilder

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +				URLQueryItem(name: "hash", value: hash),
текстовые константы для ключей запросов тоже нужно отдельно выносить

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +final class HeroesView: UIViewController
если наследуешься от `UIViewController`, то класс тоже нужно называть `HeroesViewController`, а вот протокол, можно назвать `IHeroesView`

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		self.navigationController?.navigationBar.topItem?.title = "🦸🏼‍♂️Heroes"
текстовые и числовые константы вынести в отдельное место

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +	func loadHeroes(withHeroeName name: String?) {
лучше добавить значение по умолчанию и вызвать потом метод так `self.loadHeroes()`

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		self.settingsForTableView()
можно объединить в один метод, а странно выглядят 2 одинаковых по названию метода

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		}
лучше вынести в отдельный метод. например, такой `func removeSelectionFromCell()`

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		if let indexPath = self.tableView.indexPathForSelectedRow{
пробел перед `{`

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		self.labelHeroesNotFound.font = UIFont(name: "Helvetica", size: 20)
`UIFont(name: "Helvetica", size: 20)` повторяется в проекте 9 раз 🤦🏼‍♂️

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesPresenter.swift
> +		self.dispatchGroup.enter()
🤔 а чем тут занимается `dispatchGroup`? у тебя же все операции идут последовательно

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesTableViewCell.swift
> +		self.heroeImageView.clipsToBounds = true
мне кажется, что эту настройку достаточно сделать 1 раз

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesTableViewCell.swift
> +	func settingsForImageView() {
private

2019-12-10 16:31 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesTableViewCell.swift
> +	func settingsForNameLabel() {
и тут + ниже

2019-12-13 22:36 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesTableViewCell.swift
> +		self.heroeImageView.clipsToBounds = true
fixed

2019-12-13 22:36 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesTableViewCell.swift
> +	func settingsForImageView() {
fixed

2019-12-13 22:36 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesTableViewCell.swift
> +	func settingsForNameLabel() {
fixed

2019-12-14 07:11 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Repository/Repository.swift
> +
fixed

2019-12-14 07:12 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +extension NetworkService
fixed

2019-12-14 07:13 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +				URLQueryItem(name: "hash", value: hash),
fixed

2019-12-14 07:18 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +final class HeroesView: UIViewController
fixed

2019-12-14 07:19 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		self.navigationController?.navigationBar.topItem?.title = "🦸🏼‍♂️Heroes"
fixed

2019-12-14 07:22 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +	func loadHeroes(withHeroeName name: String?) {
fixed

2019-12-14 15:34 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +	}()
fixed

2019-12-14 15:34 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		authorsNavigationController.pushViewController(authorsVC, animated: false)
fixed

2019-12-14 15:34 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Factory/Factory.swift
> +		let repository = Repository()
fixed

2019-12-14 15:34 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Repository/Repository.swift
> +	let networkService = NetworkService()
fixed

2019-12-14 15:35 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Services/NetworkService.swift
> +	private func createURL(withHeroeName heroeName: String?) -> URL? {
fixed

2019-12-14 15:36 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		self.settingsForTableView()
fixed

2019-12-14 15:52 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		}
fixed

2019-12-14 15:52 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		if let indexPath = self.tableView.indexPathForSelectedRow{
fixed

2019-12-14 15:52 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Heroes/HeroesView.swift
> +		self.labelHeroesNotFound.font = UIFont(name: "Helvetica", size: 20)
fixed

2019-12-14 15:53 UTC, Med1D commented on MarvelHeroes/MarvelHeroes/Application/AppDelegate.swift
> +		window.backgroundColor = #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1)
fixed

2019-12-15 13:35 UTC, ArtemPrivet commented
Принято ✅

2019-12-15 13:35 UTC, closed without merging