shelginskiy_igor/marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #88
Opened 2019-12-06 16:16 UTC by Engwar

Задача минимум с ужасными ошибками (описал в комите)
Исправить не получается

2019-12-08 20:05 UTC, ArtemPrivet requested changes

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Business layer/HeroesRepository.swift
> +	func getHeroes(of text: String, completion: @escaping([ResultChar]?) -> Void){
Мы обратно тоже должны возвращать result, ибо ошибки тоже важны

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Business layer/HeroesRepository.swift
> +					completion(nil)
Вместо nil нужно вернуть ошибку. Можно сделать enum с ошибками

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +	}()
А почему они все var? Разве они меняются?

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +		}()
Вот логика получения картинки должна быть в презентере, вью такое решать не должна

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +			UITableViewCell(style: .subtitle, reuseIdentifier: "comicsCell")
Вынести `comicsCell` в константы

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +		cell.textLabel?.text = comic.name
Давай сразу из презентера комикс получать

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroRouter.swift
> +	private var factory: ModulesFactory
Почему var?

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +	var activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
activityIndicator не должен торчать наружу

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +	func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
Не оставляй такие пустые срочки после открытия фигурной скобки. Мы ее как раз и ставим, чтобы не делать пустую строчку

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +	func addNavigationsVC() -> [UINavigationController] {
private

2019-12-08 20:05 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Protocols/Protocols.swift
> +	func getComics(of heroID: Int, completion: @escaping([ResultBook]?) -> Void)
Опять же, мы должны возвращать не массив, а тип Result<Success, Error>

2019-12-08 20:42 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Business layer/HeroesRepository.swift
> +	func getHeroes(of text: String, completion: @escaping([ResultChar]?) -> Void){
fixed

2019-12-08 21:39 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Business layer/HeroesRepository.swift
> +					completion(nil)
fixed

2019-12-08 21:42 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +	}()
fixed

2019-12-08 22:12 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +		}()
fised

2019-12-08 22:15 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +			UITableViewCell(style: .subtitle, reuseIdentifier: "comicsCell")
fixed

2019-12-08 22:18 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +		cell.textLabel?.text = comic.name
fixed (поправил это на момент комментария когда решал вопрос с загрузкой картинки комикса)

2019-12-08 22:18 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroRouter.swift
> +	private var factory: ModulesFactory
fixed

2019-12-08 22:19 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +	var activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
fixed

2019-12-08 22:19 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +	func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
поправил

2019-12-08 22:20 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +	func addNavigationsVC() -> [UINavigationController] {
поправил

2019-12-08 23:04 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Protocols/Protocols.swift
> +	func getComics(of heroID: Int, completion: @escaping([ResultBook]?) -> Void)
исправил

2019-12-11 08:23 UTC, ArtemPrivet requested changes

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Business layer/ComicsRepository.swift
> +typealias ComicsResult = Result<[ResultBook]?, ServiceError>
Тут не должно быть nil результата

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Business layer/ComicsRepository.swift
> +					return
Тут return не нужен в обоих случаях. Функция и так закончится

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Business layer/HeroesRepository.swift
> +typealias CharactersResult = Result<[ResultChar]?, ServiceError>
Тут тоже убрать опциональность

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroRouter.swift
> +		detailViewController.view.backgroundColor = .white
А почему это тут а не внутри контроллера?

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +	private var stubImage: UIImageView = {
Тут точно все параметры должны быть var?

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		navigationItem.title = "🦸‍♂️ Heroes"
Можно просто title = ... писать

2019-12-11 08:23 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		let naviAuthorVC = UINavigationController(rootViewController: AuthorViewController())
Надо бы создание этих контроллеров тоже в фабрику убрать

2019-12-11 10:44 UTC, MisnikovRoman requested changes
- при скроле таблицы происходит смена картинок несколько раз

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		let naviComicsVC = UINavigationController(rootViewController: ComicsViewController())
экраны нужно создавать в фабрике

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		naviComicsVC.tabBarItem.image = UIImage(named: "comic")
константы нужно вынести отдельно

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Business layer/Factory.swift
> +		presenter.getComics()
этой строчки тут точно не должно быть. запрашивать комиксы должен ViewController

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		view.addSubview(activityIndicator)
лучше максимально разгрузить viewDidLoad и все настройки вынести в отдельные методы

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		stubText.text = "Nothing found on query "
Константы вынести отдельно

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		if ifGot {
не понятно за что отвечает переменные `ifGot`

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		cell.imageView?.layer.masksToBounds = true
тут не лучшее место для изменения UI-я. либо выделять в отдельный класс ячейку, либо хотя бы отдельный приватный метод конфигурации

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		DispatchQueue(label: "loadImage", qos: .userInitiated, attributes: .concurrent).async {
перевод в бэкграунд очередь должен находится в презентере

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroPresenter.swift
> +
лишний энтер

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroPresenter.swift
> +	let loadHeroesQueue = DispatchQueue(label: "loadHeroesQueue", qos: .userInteractive, attributes: .concurrent)
а почему очередь публичная?

2019-12-11 10:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroPresenter.swift
> +						print(error)
тут вместо принта можно добавить либо ассерт, либо Алерт

2019-12-11 11:56 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Business layer/ComicsRepository.swift
> +typealias ComicsResult = Result<[ResultBook]?, ServiceError>
fix

2019-12-11 11:56 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Business layer/HeroesRepository.swift
> +typealias CharactersResult = Result<[ResultChar]?, ServiceError>
fix

2019-12-11 11:56 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Business layer/ComicsRepository.swift
> +					return
fix

2019-12-11 11:57 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroRouter.swift
> +		detailViewController.view.backgroundColor = .white
fix

2019-12-11 12:02 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +	private var stubImage: UIImageView = {
fix (исправлял такую же ошибку в детэйл, за был что здесь тоже надо константы)

2019-12-11 12:06 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		navigationItem.title = "🦸‍♂️ Heroes"
да спасибо, поправил

2019-12-11 12:29 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroPresenter.swift
> +	let loadHeroesQueue = DispatchQueue(label: "loadHeroesQueue", qos: .userInteractive, attributes: .concurrent)
fix

2019-12-11 12:30 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroPresenter.swift
> +
fix

2019-12-11 12:36 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		if ifGot {
переменная проверяет получены ли данные, которые заполняют массив героев, и в зависимости от ответа мы либо показываем таблицу или стабы

2019-12-11 12:39 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		stubText.text = "Nothing found on query "
не совсем понял, эти параметры в другой метод вынести?

2019-12-11 12:42 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		view.addSubview(activityIndicator)
вынес в отдельные методы

2019-12-11 12:45 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Business layer/Factory.swift
> +		presenter.getComics()
fixed

2019-12-11 12:48 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		naviComicsVC.tabBarItem.image = UIImage(named: "comic")
fix

2019-12-11 14:33 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		let naviAuthorVC = UINavigationController(rootViewController: AuthorViewController())
Пока стоят заглушки, после реализации второго этапа вынесу в фабрику

2019-12-11 15:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		stubText.text = "Nothing found on query "
``` swift
enum Constant {
  enum Text {
    static let stub = "Nothing found on query "
  }
}
```

2019-12-11 15:07 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		if ifGot {
=) нужно название ей поменять

2019-12-11 17:05 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		if ifGot {
fixed

2019-12-11 21:21 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		let naviAuthorVC = UINavigationController(rootViewController: AuthorViewController())
fixed

2019-12-11 21:22 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Supports/AppDelegate.swift
> +		let naviComicsVC = UINavigationController(rootViewController: ComicsViewController())
fixed

2019-12-11 21:22 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		cell.imageView?.layer.masksToBounds = true
fixed

2019-12-11 21:23 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		DispatchQueue(label: "loadImage", qos: .userInitiated, attributes: .concurrent).async {
fixed

2019-12-11 22:14 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroViewController.swift
> +		stubText.text = "Nothing found on query "
вынес все константы в отдельный энам

2019-12-11 22:30 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/HeroModule/HeroPresenter.swift
> +						print(error)
добавил алерт

2019-12-12 14:04 UTC, ArtemPrivet requested changes

2019-12-12 14:04 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +		cell.imageView?.clipsToBounds = true
А почему ты тут это задаешь? 
Давай вообще спрячем textLabel и imageView и сделаем метод, который сеттит параметры

2019-12-12 14:04 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Net/NetService.swift
> +	private var hashString: String
Почему var?

2019-12-12 18:45 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/Net/NetService.swift
> +	private var hashString: String
fix

2019-12-13 13:09 UTC, Engwar commented on MarvelHeroes/MarvelHeroes/DetailModule/DetailViewController.swift
> +		cell.imageView?.clipsToBounds = true
Я вынес в отдельный метод, но я понимаю что метод загрузки картинки должен находится в презентере, если я выношу его туда то картинка грузится  только после скрола ячейки, она постоянно так подгружается. У меня так же сделано на главном экране, там картинки подгружаются вообще только после прокручивания, хотя я делаю релоад дейта

2019-12-15 13:26 UTC, ArtemPrivet commented
Принято ✅

2019-12-15 13:26 UTC, closed without merging