medvedev_mikhail/marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #89
Opened 2019-12-06 20:44 UTC by c0dedbear

Я немного упоролся с collectionView для второго контроллера). 
Позволил некоторые вольности в UI, типа красного цвета шрифта на таббаре ну и collectionView вместо tablewView на втором экране. 
А еще у меня кончился лимит запросов по моему ключу на сегодня. Так что пока вместо результатов поиска будет выдавать сообщение о превышении лимита запросов. 

<img width="375" alt="Screenshot 2019-12-06 at 23 04 00" src="https://user-images.githubusercontent.com/21219011/70354800-98b3f600-1881-11ea-9d09-9bf1afa1b4f1.png">

**По идее должно завтра заработать.**

2019-12-08 13:33 UTC, MisnikovRoman reviewed
- при нажатии на кнопку поиска, можно было добавить активити индикатор, который бы показал пользователю, что идет процесс загрузки
- нельзя скрыть клавиатуру при заглушке "Ничего не найдено при запросе ..."

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemsDetailsRouter.swift
> +		navController.restorationIdentifier = ModulesFactory.secondaryId
У тебя каждый раз создается новый NavigationController, хотя это не нужно, если текущий контроллер показан модально

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemsDetailsRouter.swift
> +		if viewController?.navigationController?.restorationIdentifier == ModulesFactory.primaryId {
Также мне кажется, что использовать `restorationIdentifier` для того, чтобы понять что у тебя экран показан модально - не совсем правильно.
Можно, например, использовать такое расширение:
``` swift
extension UIViewController {
    var isModallyPresented: Bool {
        let presentingIsModal = presentingViewController != nil
        let presentingIsNavigation = navigationController?.presentingViewController?.presentedViewController == navigationController
        let presentingIsTabBar = tabBarController?.presentingViewController is UITabBarController

        return presentingIsModal || presentingIsNavigation || presentingIsTabBar
    }
}
```

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +			marvelItemsTableViewController.title = "🦸🏻‍♂️ Heroes"
Все текстовые и числовые константы нужно выносить отдельно (либо в этом же классе, либо в отдельное перечисление)

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +		let repository = MarvelItemsRepository(remoteDataSource: NetworkManager())
А зачем здесь и в createItemDetailsModule создает отдельный `NetworkManager()`?
Лучше у ModulesFactory создать приватные переменные и их потом использовать:
``` swift
private let networkService = NetworkService()
```
Также можно было сервисы и репозитории создавать в `AppDelegate`, а потом инжектить в ModulesFactory

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +		let router = MarvelItemsListRouter(modulesFactory: self, viewController: nil)
не нашел создания `MarvelItemsListRouter`, куда бы передавался viewController при инициализации. `viewController: nil` - нужно убрать

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +		let presenter = MarvelItemsListPresenter(repository: repository, router: router, heroesListVC: nil)
тоже самое для presenter'a

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsListPresenter.swift
> +	weak var itemsList: MarvelItemsTableViewController?
vc не закрыт протоколом

2019-12-08 13:33 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +			marvelItemsTableViewController.title = "🦸🏻‍♂️ Heroes"
Плюс, я бы не оставлял настройку title контроллера здесь, а передал бы в презентер `MarvelItemType`, а вот там уже бы менял настройки UI

2019-12-08 16:39 UTC, MisnikovRoman requested changes

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkService.swift
> +	private var dataTask: URLSessionDataTask?
Насколько я понял, в текущей реализации невозможно запустить несколько запросов одновременно. Но если там понадобится обработать сразу два запроса на одном экране, они смогут выполнится только последовательно, что лишает нашу систему гибкости

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkServiceError.swift
> +	case failJSONSerialization
Довольно, странно что NetworkService не занимается сериализацией, но имеет ошибку десериализации

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Repositories/NetworkManager.swift
> +		 jsonDataFetcher: IJSONDataFetchable = JSONDataFetcher()
А почему аргументы имеют значение по умолчанию, а не пробрасываются из фабрики

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Repositories/NetworkManager.swift
> +	func makeApiURL(addingPathToComponents: String, queryItems: [URLQueryItem], withSearchText: String) -> URL? {
можно сделать приватной

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemDetailsPresenter.swift
> +			repository.remoteDataSource.fetchMarvelItems(
ты не должен обращаться напрямую к датасорсу, все должно проксироваться через репозиторий. т.е в репозитории должен быть метод `.marvelItems(:)`, а репозиторий должен обращаться уже к `DataSource`

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemDetailsPresenter.swift
> +						self?.detailVC?.header?.imageView.alpha = 1
презентер не должен напрямую общаться с компонентами UIKit

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemDetailsPresenter.swift
> +		if item as? Comics != nil { type = .comics }
``` swift 
switch item {
case is Hero:   type = .heroes
case is Author: type = .authors
case is Comics: type = .comics
default:        assertionFailure("Неизвестный тип")
}
```

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/JSONDataFetcher.swift
> +final class JSONDataFetcher: IJSONDataFetchable
либо `IJSONDataFetcher` либо `JSONDataFetchable`

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/JSONDataFetcher.swift
> +					}
я бы перенес это в презентер

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkServiceProtocols.swift
> +	func sendJSONDataWithModelAsResponse<T: Codable, R: Decodable>(url: URL,
этот метод нигде не используется - YAGNI

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Repositories/MarvelItemsRepository.swift
> +
В твоей реализации необходимость в репозитории отсутствует. Я уже писал, что `remoteDataSource` должен быть приватным

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Models/Hero.swift
> +	thumbnail: Thumbnail(path: "", thumbnailExtension: ""))
так переносить не стоит, если делаешь перенос - тогда всех аргументов:
``` swift
static let empty = Hero(id: 0, 
                        name: "Error", 
                        description: "",
                        thumbnail: Thumbnail(path: "", thumbnailExtension: ""))
```

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Models/Comics.swift
> +	var fullName: String? { nil }
эт довольно странно выглядит - вычисляемые переменные, которые всегда nil. Зачем они тут?

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/Views/Cells/RoundedMarvelItemTableViewCell.swift
> +	override func setConstraints() {
В методе много повторяющегося кода

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +		perform(#selector(self.reload(_:)), with: searchController.searchBar, afterDelay: 0.7)
Мне не очень нравится такое решение, лучше использовать GCD и реализовать отдельную сущность, которая будет тротлить запросы

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +
данный метод точно нужно переделывать - разбивать на несколько методов или еще что-то, но конфигурировать одновременно 2 разные ячейки - плохая идея

2019-12-08 16:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +			RoundedMarvelItemTableViewCell.id) as? RoundedMarvelItemTableViewCell else { return portraitCell }
ну и тут скорее нужно использовать `if let` чем guard

2019-12-09 14:49 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemsDetailsRouter.swift
> +		navController.restorationIdentifier = ModulesFactory.secondaryId
Да, не подумал об этом... Поправил.

2019-12-09 14:49 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemsDetailsRouter.swift
> +		if viewController?.navigationController?.restorationIdentifier == ModulesFactory.primaryId {
Исправил. Спасибо за наводку.

2019-12-09 14:49 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +			marvelItemsTableViewController.title = "🦸🏻‍♂️ Heroes"
Сделано.

2019-12-09 14:49 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +		let repository = MarvelItemsRepository(remoteDataSource: NetworkManager())
Поправил.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +		let router = MarvelItemsListRouter(modulesFactory: self, viewController: nil)
Сделал.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +		let presenter = MarvelItemsListPresenter(repository: repository, router: router, heroesListVC: nil)
Сделал.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsListPresenter.swift
> +	weak var itemsList: MarvelItemsTableViewController?
Позакрывал.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +			marvelItemsTableViewController.title = "🦸🏻‍♂️ Heroes"
Согласен, так логичнее. Но если меняешь title, то почему то автоматом меняется и title у в таббаре. То есть нужно будет переназначать title у табБарАйтемов второй раз.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkService.swift
> +	private var dataTask: URLSessionDataTask?
Не совсем понимаю по каким признакам это определить. В функции request создается новый дататаск, с возможностью отменять предыдущий запрос либо нет.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkServiceError.swift
> +	case failJSONSerialization
В какой то момент разработки он ей занимался =))

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Repositories/NetworkManager.swift
> +		 jsonDataFetcher: IJSONDataFetchable = JSONDataFetcher()
Исправил.

2019-12-09 14:50 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Repositories/NetworkManager.swift
> +	func makeApiURL(addingPathToComponents: String, queryItems: [URLQueryItem], withSearchText: String) -> URL? {
ок

2019-12-09 14:51 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemDetailsPresenter.swift
> +						self?.detailVC?.header?.imageView.alpha = 1
Исправил, теперь общается через функции типа "setSomething",  reload и т.д.

2019-12-09 14:51 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemDetailsPresenter.swift
> +			repository.remoteDataSource.fetchMarvelItems(
Получается что у меня была лишняя прослойка.

2019-12-09 14:51 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemDetails/ItemDetailsPresenter.swift
> +		if item as? Comics != nil { type = .comics }
Поправил.

2019-12-09 14:51 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/JSONDataFetcher.swift
> +final class JSONDataFetcher: IJSONDataFetchable
Ок.

2019-12-09 14:51 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/JSONDataFetcher.swift
> +					}
Презентеров несколько и запросов несколько, решил что лучше прописать один раз при отправке запроса чем копировать везде.

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkServiceProtocols.swift
> +	func sendJSONDataWithModelAsResponse<T: Codable, R: Decodable>(url: URL,
Удалил.

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Repositories/MarvelItemsRepository.swift
> +
Я понял, у меня networkManager это и есть по сути репозиторий.

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Models/Hero.swift
> +	thumbnail: Thumbnail(path: "", thumbnailExtension: ""))
Учту.

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Models/Comics.swift
> +	var fullName: String? { nil }
Это для того чтобы модели могли подписаться под общий протокол IMarvelItemDetails, который используется на втором экране. Чтобы не проверять какой тип айтемы пришел.
Например у Hero нет fullname или title, но есть name, соотвественно эти свойства всегда будут nil. Сейчас задумался о том, что можно было сделать вообще одну модель и определять тип по свойствам...

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/Views/Cells/RoundedMarvelItemTableViewCell.swift
> +	override func setConstraints() {
Избавился от этого класса.

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +		perform(#selector(self.reload(_:)), with: searchController.searchBar, afterDelay: 0.7)
Пробовал сначала сам через asyncAfter, но что-то там не работало. Потом нашел такую реализацию просторах stackoverflow...

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +
Переделал. Не знаю насколько хорошо менять констрейнты imageView ячейки в данном методе, но таким образом я избавился от класса наследника и теперь у меня только одна ячейка.

2019-12-09 14:52 UTC, c0dedbear commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +			RoundedMarvelItemTableViewCell.id) as? RoundedMarvelItemTableViewCell else { return portraitCell }
Теперь только одна ячейка.

2019-12-09 14:52 UTC, c0dedbear commented
> * при нажатии на кнопку поиска, можно было добавить активити индикатор, который бы показал пользователю, что идет процесс загрузки
> * нельзя скрыть клавиатуру при заглушке "Ничего не найдено при запросе ..."

Попробую парировать 😃:
1. На этом экране мне показалось достаточно системного activity indicator так как данные с поиском грузятся достаточно быстро при норм интернете: а при плохом юзер увидит по статус бару что приложение что то грузит так фокус его внимания будет на строке поиска.

2. Клавиатура скрывается либо при нажатии кнопки Search на клавиатуре, либо по кнопке Cancel на searchBar при любом раскладе. Да и в  условиях задания вроде бы этого не было, не стал с этим заморачиваться.

2019-12-09 18:39 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Application/ModulesFactory.swift
> +			marvelItemsTableViewController.title = "🦸🏻‍♂️ Heroes"
Настройку иконки для таббара я бы тоже перенес в контроллер

2019-12-09 18:44 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Services/NetworkService/NetworkService.swift
> +	private var dataTask: URLSessionDataTask?
у тебя NetworkService выступает в роли корневой сущности, которая ходит в сеть. От нее зависят, например, `JSONDataFetcher` и `NetworkManager` и довольно логично чтобы в NetworkService'e могли обрабатываться сразу несколько запросов, но у тебя такое невозможно, поскольку каждый новый dataTask отменяет предыдущий

2019-12-09 18:46 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Models/Comics.swift
> +	var fullName: String? { nil }
просто обычно протокол говорит, что у объекта есть какие-то свойства, а тут получается, наоборот

2019-12-09 18:48 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Modules/MarvelItemsList/MarvelItemsTableViewController.swift
> +		perform(#selector(self.reload(_:)), with: searchController.searchBar, afterDelay: 0.7)
я вот не люблю swift'jdsq код мешать с сущностями ObjC. Вот, например, есть статья как сделать тротлер на GCD http://danielemargutti.com/2017/10/19/throttle-in-swift/

2019-12-09 18:53 UTC, MisnikovRoman commented
> > * при нажатии на кнопку поиска, можно было добавить активити индикатор, который бы показал пользователю, что идет процесс загрузки
> > * нельзя скрыть клавиатуру при заглушке "Ничего не найдено при запросе ..."
> 
> Попробую парировать 😃:
> 
> 1. На этом экране мне показалось достаточно системного activity indicator так как данные с поиском грузятся достаточно быстро при норм интернете: а при плохом юзер увидит по статус бару что приложение что-то грузит, так как фокус его внимания будет на строке поиска.
> 2. Клавиатура скрывается либо при нажатии кнопки Search на клавиатуре, либо по кнопке Cancel на searchBar при любом раскладе. Да и в  условиях задания вроде бы этого не было, не стал с этим заморачиваться.

со вторым солгласен, а вот с первым нет 😁
судить по идеальным условиям не стоит, у меня дома при довольно хорошем интернете белый экран вызвал недоумение. В любом случае, это не критично, но в большинстве приложений, которые я встречал, не было такого подхода

2019-12-09 18:53 UTC, closed without merging

2019-12-09 18:54 UTC, MisnikovRoman commented
Принято