kozlov_stanislav/marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #90
Opened 2019-12-06 21:22 UTC by artbleymy

2019-12-06 22:03 UTC, artbleymy commented
Ура, трэвис побежден

2019-12-07 10:57 UTC, ArtemPrivet requested changes

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Factory/ModuleFactory.swift
> +	private var repository: Repository
А почеум var?

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Presenter/EntityDetailsPresenter.swift
> +	func getRecord(index: Int) -> IEntity
Вообще можно заменить все функции `get` на computed property. Так будет по свифтовому

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Presenter/EntityDetailsPresenter.swift
> +	private var entityType: EntityType
Вроде как currentRecord и entityType можно сделать let

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Presenter/EntityDetailsPresenter.swift
> +			localRepository.loadAccessoryByEntityID(from: directory) {(result: Result<ComicsResponse, ServiceError>) in
weak self

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Presenter/EntityDetailsPresenter.swift
> +			localRepository.loadAccessoryByEntityID(from: directory) {(result: Result<AuthorResponse, ServiceError>) in
Тоже weak self

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Utils/Cell.swift
> +	}
Лучше сделать метод, который будет конфигурировать эти параметры, а не оставлять их доступными извне

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Utils/Cell.swift
> +	}
Лишняя функция

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Utils/Constants.swift
> +	static let limit = 100
На будущее, лучше как-то константы группировать по смыслу, а то у тебя тут всё перемешано

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Utils/UITableView+EmptyImage.swift
> +		self.backgroundView = view
Лучше создать отдельный класс EmptyImageView, создать его во ViewContoller'e и уже подставлять, если таблица пустая

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/View/DetailsView/DetailsView.swift
> +	private var space = Constants.space
Многое что var, можно сделать let

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/View/DetailsView/DetailsView.swift
> +		let cell = tableView.dequeueReusableCell(withIdentifier: "comicsCell", for: indexPath)
Identifier в константы

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/View/DetailsView/DetailsView.swift
> +							}
Перенести логику из View

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/View/DetailsView/EntityDetailsViewController.swift
> +	}
loadView лучше перенести наверх, так как это первый метод в ЖЦ контроллера

2019-12-07 10:57 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/View/DetailsView/EntityDetailsViewController.swift
> +		}
Ну ты понял

2019-12-07 11:00 UTC, ArtemPrivet requested changes
Нужны изменения

2019-12-08 10:07 UTC, artbleymy commented
Все поправил, вью контроллеры кастомные полностью убрал, о вью контроллере теперь знает только роутер

2019-12-08 16:53 UTC, ArtemPrivet requested changes

2019-12-08 16:53 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Factory/ModuleFactory.swift
> +		viewController.title = presenter.getCurrentRecord().showingName
title точно не тут надо задавать. В контроллере надо брать title из презентера

2019-12-08 16:53 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/View/DetailsView/DetailsView.swift
> +	private var repository: Repository?
Ты же repository в ините задаешь, почему тогда он var?

2019-12-10 08:31 UTC, closed without merging