belov_anton/marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #91
Opened 2019-12-06 23:40 UTC by belannik

Пока только минимум. Если можно будет, то постараюсь чуть попозже сделать следующую стадию и поправить недочёты

2019-12-07 11:34 UTC, ArtemPrivet requested changes

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +	private var detailPresenter: DetailScreenPresenter
let

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +	private let tableView = UITableView()
Переменные вверх класса нужно убирать

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		self.tableView.frame = CGRect(origin: .zero, size: screenSize)
Таблицу нужно тоже констрейнтами привязать

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		}
У тебя размер Image зависит от размера текста. Нужно тоже констреинты задать

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +	}
Приватные функции вниз файла нужно убирать

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +			}
View не должна переключать очереди, это роль презентера

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreenPresenter.swift
> +	let networkService = NetworkService()
Надо бы private сделать

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreenPresenter.swift
> +	var description: String {
Либо эти свойства нужно сделать private либо вынести в протокол тоже

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/HeroesScreenPresenter.swift
> +	}
Переходы нужно делать через Router

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/MainScreen.swift
> +	let presenter = HeroesScreenPresenter()
Должен быть private

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Network/NetworkProtocol.swift
> +	func getComicsAtHeroesID(id: String, callBack: @escaping (SeriesDataWrapper) -> Void)
Нужно в callback возвращать тип Result<Value, Error>, а то у тебя тут только положительный вариант есть, но ведь бывают и ошибки

2019-12-07 11:34 UTC, ArtemPrivet commented on MarvelHeroes/MarvelHeroes/Network/NetworkService.swift
> +				fatalError(error.localizedDescription)
Ну фатал error на запрос это жестко

2019-12-11 11:06 UTC, MisnikovRoman requested changes

2019-12-11 11:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		self.tableView.reloadData()
reload тут не нужен

2019-12-11 11:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		imageView.frame = CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight / 1.8)
а почему не констрейнты?

2019-12-11 11:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		setupTableView()
почему это не во viewDidLoad?

2019-12-11 11:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +extension DetailScreenViewController: UITableViewDataSource, UITableViewDelegate
лучше разбивать на отдельные extension'ы UITableViewDataSource и UITableViewDelegate

2019-12-11 11:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreenPresenter.swift
> +	func getComicsImageData(indexPath: IndexPath, callBack: @escaping (Data) -> Void) {
а почему не передаешь ошибки?

2019-12-11 20:07 UTC, belannik commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		setupTableView()
Для размещения картинки на тейблвью нужны были размеры экрана. Я подумал делать всё это во viewDidAppear, раз всё равно активити индикатор висеть будет

2019-12-11 20:18 UTC, belannik commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		imageView.frame = CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight / 1.8)
А зачем? imageView потом ведь в хедер на тейблвью ляжет

2019-12-11 20:18 UTC, belannik commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +extension DetailScreenViewController: UITableViewDataSource, UITableViewDelegate
Исправил

2019-12-11 20:18 UTC, belannik commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreenPresenter.swift
> +	func getComicsImageData(indexPath: IndexPath, callBack: @escaping (Data) -> Void) {
Исправил

2019-12-11 20:19 UTC, belannik commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		self.tableView.reloadData()
Убрано

2019-12-11 20:21 UTC, belannik commented
Я крч тут почти всё поменял, но в изменениях учитывал предыдущие ошибки и внёс исправления :)

2019-12-11 21:04 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		imageView.frame = CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight / 1.8)
чтобы не было проблем в будущем, чтобы не делать настройки во viewWillAppear

2019-12-11 21:04 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		setupTableView()
опять же можно использовать констрейнты. при чем тут активити индикатор?

2019-12-11 21:05 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/HeroesSearchScreen/DetailScreen/DetailScreen.swift
> +		imageView.frame = CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight / 1.8)
чтобы не словить проблем в будущем, чтобы не делать настройки во viewWillAppear

2019-12-11 21:13 UTC, MisnikovRoman requested changes

2019-12-11 21:13 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/MainScreen/DetailScreen/DetailViewController.swift
> +			self.tableView.heightAnchor.constraint(equalToConstant: self.view.frame.height - height),
сомнительное решение

2019-12-11 21:13 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/MainScreen/DetailScreen/DetailViewController.swift
> -		self.tableView.translatesAutoresizingMaskIntoConstraints = false
а почему ты убираешь эту настройку? констрейнты же остаются

2019-12-11 22:54 UTC, belannik commented on MarvelHeroes/MarvelHeroes/MainScreen/DetailScreen/DetailViewController.swift
> -		self.tableView.translatesAutoresizingMaskIntoConstraints = false
Там в начале функции есть еще одна такая же :)

2019-12-15 13:46 UTC, ArtemPrivet commented
Принято ✅

2019-12-15 13:46 UTC, closed without merging