marvel-heroes
ArtemPrivet/FocusStartHomeworks pull request #93
Opened 2019-12-09 00:34 UTC by anna-belousova

Не успела доделать, завтра добавлю tableview с комиксами

2019-12-09 20:06 UTC, MisnikovRoman requested changes
- ячейки несколько раз меняют картинки при прокрутке

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +final class NetworkService
Файл лучше было назвать `NetworkService.swift`

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +	private let privateKey = "bdd47bde424e1c094f2bf0be737288689439827a"
Константы нужно вынести в отдельное перечисление

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +			if let newError = error {
минор, можно просто `if let error = error`, чтобы не создавать переменную с новым именем

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +		URLQueryItem(name: "hash", value: hash),
тут тоже лучше вынести константы в отдельные переменные

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +			}() else { return }
отступы

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +		let query = [
`let queryItems = [`

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +			guard let baseUrl = baseUrl else { return nil }
вложенные guard'ы плохо читаются. Лучше так
``` swift
guard let baseUrl = baseUrl else { return }
var urlComponents = URLComponents(url: baseUrl, resolvingAgainstBaseURL: true)
urlComponents?.queryItems = query
guard let url = urlComponents?.url else { return }
```

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/NetworkService/ConvertToMd5.swift
> +public func calculateMD5(_ bytes: [Byte]) -> Digest {
Лучше не оставлять публичные методы доступные всем. Нужно обернуть это в какую-нибудь сущность

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/NetworkService/ConvertToMd5.swift
> +public func calculateMD5(_ bytes: [Byte]) -> Digest {
В целом есть более простое решение для нахождения md5
``` swift
import Foundation
import CommonCrypto

extension String
{
  var md5_: String {
    let data = Data(self.utf8)
    let hash = data.withUnsafeBytes { (bytes: UnsafeRawBufferPointer) -> [UInt8] in
      var hash = [UInt8](repeating: 0, count: Int(CC_MD5_DIGEST_LENGTH))
      CC_MD5(bytes.baseAddress, CC_LONG(data.count), &hash)
      return hash
    }
    return hash.map { String(format: "%02x", $0) }.joined()
  }
}
```

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/Model/CharacterRepository.swift
> +	init(jsonService: INetworkService) {
думаю, тут нужно заменить `jsonService` на `networkService`

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterRouter.swift
> +		viewController?.view.backgroundColor = .white
настройки UI не делаются в роутере, нужно перенести во ViewController

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		controller.searchBar.placeholder = "Find character"
Вынести константу отдельно

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +	}()
private let notFoundImage = UIImageView(image: #imageLiteral(resourceName: "Снимок экрана 2019-11-29 в 22.57.13"))

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		label.font.withSize(25)
Числовые константы тоже нужно выносить отдельно

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		//stackView.spacing = 5
такие комментарии нужно убирать перед пулом)

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +	private lazy var nothingFoundLabel: UILabel = {
а зачем тут lazy?

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		_ = searchController.searchBar
а это зачем?

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		view.backgroundColor = .white
можно вынести в отдельный метод, чтобы разгрузить `viewDidLoad`

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +	private func showNotFound() {
можно перенести в extension c приватными методами

2019-12-09 20:06 UTC, MisnikovRoman commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +			characters[indexPath.row].description.isEmpty ? "No info" : characters[indexPath.row].description
лучше переносить так
``` swift
cell?.descriptionLabel.text = characters[indexPath.row].description.isEmpty
  ? "No info" 
  : characters[indexPath.row].description
```

2019-12-14 21:21 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +final class NetworkService
fixed

2019-12-14 21:21 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +	private let privateKey = "bdd47bde424e1c094f2bf0be737288689439827a"
fixed

2019-12-14 21:22 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +			}() else { return }
переписала этот код

2019-12-14 21:22 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +		let query = [
fixed

2019-12-14 21:22 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +			guard let baseUrl = baseUrl else { return nil }
fixed

2019-12-14 21:22 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/NetworkService/ConvertToMd5.swift
> +public func calculateMD5(_ bytes: [Byte]) -> Digest {
Поменяла код для md5

2019-12-14 21:23 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/CharacterRepository.swift
> +	init(jsonService: INetworkService) {
fixed

2019-12-14 21:23 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterRouter.swift
> +		viewController?.view.backgroundColor = .white
во ViewController есть эта настройка UI, забыла убрать из роутера
fixed

2019-12-14 21:23 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		controller.searchBar.placeholder = "Find character"
fixed

2019-12-14 21:24 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +	}()
забыла поменять) fixed

2019-12-14 21:24 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		label.font.withSize(25)
fixed

2019-12-14 21:24 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		//stackView.spacing = 5
fixed

2019-12-14 21:24 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +	private lazy var nothingFoundLabel: UILabel = {
сделала по аналогии с другими лэйблами, но никаких данных в него извне не поступало, lazy не был нужен. Сейчас вынесла размер шрифта в отдельную константу и lazy понадобился

2019-12-14 21:24 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		_ = searchController.searchBar
что-то с searchBar'ом было не так, пыталась исправить и не убрала, когда поправила.
fixed

2019-12-14 21:25 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +		view.backgroundColor = .white
fixed

2019-12-14 21:25 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +	private func showNotFound() {
fixed

2019-12-14 21:25 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/CharacterModule/CharacterViewController.swift
> +			characters[indexPath.row].description.isEmpty ? "No info" : characters[indexPath.row].description
fixed

2019-12-14 21:26 UTC, anna-belousova commented on MarvelHeroes/MarvelHeroes/Model/JsonService.swift
> +		URLQueryItem(name: "hash", value: hash),
Каждый URLQueryItem в отдельную константу?

2019-12-15 13:45 UTC, ArtemPrivet commented
Принято ✅

2019-12-15 13:45 UTC, closed without merging